import fs from "fs";
import path from "path";
import { PartItem, RetailerQuote } from "../types";

export const RETAILERS = [
  {
    id: "ret-shopee",
    name: "Shopee MY",
    slug: "shopee-my",
    isActive: true,
  },
  {
    id: "ret-lazada",
    name: "Lazada MY",
    slug: "lazada-my",
    isActive: true,
  },
  {
    id: "ret-pcbyte",
    name: "PC Byte Malaysia",
    slug: "pcbyte-my",
    isActive: true,
  },
  {
    id: "ret-idealtech",
    name: "Ideal Tech PC",
    slug: "idealtech-my",
    isActive: true,
  },
  {
    id: "ret-carousell",
    name: "Carousell MY",
    slug: "carousell-my",
    isActive: true,
    isMarketplace: true,
  },
  {
    id: "ret-mudah",
    name: "Mudah.my",
    slug: "mudah-my",
    isActive: true,
    isMarketplace: true,
  },
  {
    id: "ret-lowyat",
    name: "Lowyat Garage",
    slug: "lowyat-garage",
    isActive: true,
    isMarketplace: true,
  },
];

const RAW_SEED_PARTS: any[] = [
  // ==========================================
  // CPUS
  // ==========================================
  {
    id: "cpu-ryzen-3600",
    slug: "amd-ryzen-5-3600",
    name: "AMD Ryzen 5 3600 6-Core Processor",
    brand: "AMD",
    model: "Ryzen 5 3600",
    type: "CPU",
    benchmarkScore: 17800,
    bestPriceMyr: 220,
    bestNewPriceMyr: undefined,
    bestUsedPriceMyr: 220,
    hasUsedListings: true,
    inStock: true,
    specs: {
      socket: "AM4",
      tdpWattage: 65,
      cores: 6,
      threads: 12,
      baseClockGhz: 3.6,
      boostClockGhz: 4.2,
      integratedGpu: false,
      coolerIncluded: true,
    },
    marketPricing: {
      usedRange: { min: 190, max: 240, typical: 220 },
      fairTargetPriceMyr: 210,
      availability: "discontinued_used_only",
    },
    opinion: {
      verdict: "Legendary budget 6-core chip. Discontinued brand-new, but an unbeatable sub-RM220 secondary market buy for ultra-cheap gaming rigs.",
      recommendation: "must_buy_used",
      recommendationLabel: "Must Buy Second-Hand",
      pros: ["Sub-RM220 price point", "Fits dirt-cheap A320 and B450 motherboards", "Solid 1080p esports performance"],
      cons: ["PCIe 4.0 only on B550/X570", "Slower single-core speed than Ryzen 5000"],
      targetResolution: "1080p Budget",
      upgradeAdvice: "Pair with an affordable B450 motherboard and 16GB DDR4. Upgrade later to Ryzen 5 5600 or 5700X3D without changing board.",
      tierRanking: "B",
    },
  },
  {
    id: "cpu-ryzen-5600",
    slug: "amd-ryzen-5-5600",
    name: "AMD Ryzen 5 5600 6-Core Processor",
    brand: "AMD",
    model: "Ryzen 5 5600",
    type: "CPU",
    benchmarkScore: 21500,
    bestPriceMyr: 320,
    bestNewPriceMyr: 449,
    bestUsedPriceMyr: 320,
    hasUsedListings: true,
    inStock: true,
    specs: {
      socket: "AM4",
      tdpWattage: 65,
      cores: 6,
      threads: 12,
      baseClockGhz: 3.5,
      boostClockGhz: 4.4,
      integratedGpu: false,
      coolerIncluded: true,
    },
    marketPricing: {
      newRange: { min: 430, max: 480, typical: 449 },
      usedRange: { min: 290, max: 340, typical: 320 },
      fairTargetPriceMyr: 310,
      availability: "abundant",
    },
    opinion: {
      verdict: "The absolute benchmark for price-to-performance on AM4. Delivers exceptional 1080p and 1440p gaming smoothness at 65W power consumption.",
      recommendation: "must_buy_used",
      recommendationLabel: "High Value Second-Hand",
      pros: ["Superb gaming performance per Ringgit", "Low 65W TDP runs cool on bundled heatsink", "Wide compatibility with budget B450/B550 boards"],
      cons: ["Platform is AM4 end-of-life for new architectures", "No integrated graphics"],
      targetResolution: "1080p High",
      upgradeAdvice: "Pair with a B550M board and 3200MHz DDR4. Handles graphics cards up to RTX 4070 or RX 7800 XT before significant CPU bottlenecking occurs.",
      tierRanking: "S",
    },
  },
  {
    id: "cpu-ryzen-5700x3d",
    slug: "amd-ryzen-7-5700x3d",
    name: "AMD Ryzen 7 5700X3D 8-Core 3D V-Cache Processor",
    brand: "AMD",
    model: "Ryzen 7 5700X3D",
    type: "CPU",
    benchmarkScore: 26800,
    bestPriceMyr: 680,
    bestNewPriceMyr: 889,
    bestUsedPriceMyr: 680,
    hasUsedListings: true,
    inStock: true,
    specs: {
      socket: "AM4",
      tdpWattage: 105,
      cores: 8,
      threads: 16,
      baseClockGhz: 3.0,
      boostClockGhz: 4.1,
      integratedGpu: false,
      coolerIncluded: false,
    },
    marketPricing: {
      newRange: { min: 860, max: 940, typical: 889 },
      usedRange: { min: 650, max: 730, typical: 680 },
      fairTargetPriceMyr: 670,
      availability: "moderate",
    },
    opinion: {
      verdict: "The ultimate endgame gaming CPU for existing AM4 owners. 96MB 3D V-Cache eliminates 1% low frame drops in competitive games like Valorant, CS2, and MMOs.",
      recommendation: "must_buy_used",
      recommendationLabel: "Best Drop-In AM4 Upgrade",
      pros: ["Massive 96MB L3 cache boosts 1% low FPS", "Drop-in upgrade for existing AM4 motherboards", "Beats many newer CPUs in sim/strategy games"],
      cons: ["No bundled cooler", "Modest clock speeds for raw non-gaming rendering"],
      targetResolution: "1440p Sweet Spot",
      upgradeAdvice: "Requires a quality dual-tower air cooler (Thermalright PA120). Upgrade your BIOS before installing into existing B450 or B550 boards.",
      tierRanking: "S",
    },
  },
  {
    id: "cpu-ryzen-7500f",
    slug: "amd-ryzen-5-7500f",
    name: "AMD Ryzen 5 7500F 6-Core AM5 Processor",
    brand: "AMD",
    model: "Ryzen 5 7500F",
    type: "CPU",
    benchmarkScore: 26900,
    bestPriceMyr: 520,
    bestNewPriceMyr: 649,
    bestUsedPriceMyr: 520,
    hasUsedListings: true,
    inStock: true,
    specs: {
      socket: "AM5",
      tdpWattage: 65,
      cores: 6,
      threads: 12,
      baseClockGhz: 3.7,
      boostClockGhz: 5.0,
      integratedGpu: false,
      coolerIncluded: true,
    },
    marketPricing: {
      newRange: { min: 620, max: 680, typical: 649 },
      usedRange: { min: 490, max: 550, typical: 520 },
      fairTargetPriceMyr: 510,
      availability: "abundant",
    },
    opinion: {
      verdict: "The most economical entry ticket into the AM5 ecosystem. Performs within 3% of the Ryzen 5 7600 at a lower price point by omitting the weak iGPU.",
      recommendation: "safe_buy_new",
      recommendationLabel: "Best AM5 Value Entry",
      pros: ["Modern Zen 4 architecture with PCIe 5.0 support", "Long AM5 motherboard upgrade roadmap through 2027+", "Extremely efficient 65W operation"],
      cons: ["Requires DDR5 RAM (cannot reuse DDR4)", "No integrated display out for troubleshooting"],
      targetResolution: "1440p Sweet Spot",
      upgradeAdvice: "Pair with a budget B650M board (ASRock B650M-HDV) and 32GB DDR5 6000MHz CL30. Clean upgrade path to future X3D chips.",
      tierRanking: "S",
    },
  },
  {
    id: "cpu-ryzen-7800x3d",
    slug: "amd-ryzen-7-7800x3d",
    name: "AMD Ryzen 7 7800X3D 8-Core 3D V-Cache Processor",
    brand: "AMD",
    model: "Ryzen 7 7800X3D",
    type: "CPU",
    benchmarkScore: 34500,
    bestPriceMyr: 1390,
    bestNewPriceMyr: 1799,
    bestUsedPriceMyr: 1390,
    hasUsedListings: true,
    inStock: true,
    specs: {
      socket: "AM5",
      tdpWattage: 120,
      cores: 8,
      threads: 16,
      baseClockGhz: 4.2,
      boostClockGhz: 5.0,
      integratedGpu: true,
      coolerIncluded: false,
    },
    marketPricing: {
      newRange: { min: 1720, max: 1920, typical: 1799 },
      usedRange: { min: 1350, max: 1480, typical: 1390 },
      fairTargetPriceMyr: 1380,
      availability: "moderate",
    },
    opinion: {
      verdict: "The undisputed gaming king. Crushes Intel flagships in gaming efficiency, consuming half the wattage while delivering the highest minimum frame rates in modern titles.",
      recommendation: "enthusiast_tier",
      recommendationLabel: "Enthusiast Flagship",
      pros: ["Fastest pure gaming CPU in existence", "Remarkable power efficiency (~60W typical gaming load)", "Single CCD eliminates scheduling latency"],
      cons: ["Premium price point", "Lower productivity multi-core throughput than Core i7/i9"],
      targetResolution: "4K Enthusiast",
      upgradeAdvice: "Ideal companion for RTX 4070 Ti Super, RTX 4080 Super, or RTX 4090. Pair with DDR5 6000 CL30 with EXPO profile enabled.",
      tierRanking: "S",
    },
  },
  {
    id: "cpu-i5-12400f",
    slug: "intel-core-i5-12400f",
    name: "Intel Core i5-12400F 6-Core LGA1700 Processor",
    brand: "Intel",
    model: "Core i5-12400F",
    type: "CPU",
    benchmarkScore: 19800,
    bestPriceMyr: 320,
    bestNewPriceMyr: 459,
    bestUsedPriceMyr: 320,
    hasUsedListings: true,
    inStock: true,
    specs: {
      socket: "LGA1700",
      tdpWattage: 65,
      cores: 6,
      threads: 12,
      baseClockGhz: 2.5,
      boostClockGhz: 4.4,
      integratedGpu: false,
      coolerIncluded: true,
    },
    marketPricing: {
      newRange: { min: 430, max: 480, typical: 459 },
      usedRange: { min: 300, max: 350, typical: 320 },
      fairTargetPriceMyr: 315,
      availability: "abundant",
    },
    opinion: {
      verdict: "Intel's most resilient budget processor. Six pure Golden Cove Performance cores with no E-core scheduling quirks. Supports both cheap DDR4 and modern DDR5.",
      recommendation: "must_buy_used",
      recommendationLabel: "High Value Intel Used",
      pros: ["Zero E-core scheduling issues in older games", "Runs on cheap H610 motherboards", "Supports DDR4 for low-cost total platform price"],
      cons: ["Locked multiplier (no overclocking)", "Intel stock cooler gets noisy under load"],
      targetResolution: "1080p High",
      upgradeAdvice: "Pair with an MSI H610M-E or B760M-D4 board and DDR4 3200MHz RAM. Replace stock cooler with a RM60 single-tower heatsink.",
      tierRanking: "A",
    },
  },
  {
    id: "cpu-i5-13600kf",
    slug: "intel-core-i5-13600kf",
    name: "Intel Core i5-13600KF 14-Core High-Performance Processor",
    brand: "Intel",
    model: "Core i5-13600KF",
    type: "CPU",
    benchmarkScore: 38200,
    bestPriceMyr: 820,
    bestNewPriceMyr: 1189,
    bestUsedPriceMyr: 820,
    hasUsedListings: true,
    inStock: true,
    specs: {
      socket: "LGA1700",
      tdpWattage: 125,
      cores: 14,
      threads: 20,
      baseClockGhz: 3.5,
      boostClockGhz: 5.1,
      integratedGpu: false,
      coolerIncluded: false,
    },
    marketPricing: {
      newRange: { min: 1140, max: 1260, typical: 1189 },
      usedRange: { min: 780, max: 870, typical: 820 },
      fairTargetPriceMyr: 800,
      availability: "moderate",
    },
    opinion: {
      verdict: "Outstanding dual-threat workhorse. 6 Performance cores + 8 Efficiency cores make it blitz both heavy gaming and video rendering / code compilation.",
      recommendation: "must_buy_used",
      recommendationLabel: "Workstation & Gaming Pick",
      pros: ["Massive multi-threaded processing power", "High 5.1GHz single-core burst speed", "Excellent Adobe Premiere and Blender performance"],
      cons: ["Draws up to 181W under sustained multicore loads", "Requires 240mm AIO or beefy dual-tower cooler"],
      targetResolution: "Workstation / Production",
      upgradeAdvice: "Verify motherboard BIOS has latest Intel microcode 0x129/0x12B voltage baseline updates applied. Pair with a B760 or Z790 board.",
      tierRanking: "A",
    },
  },

  // ==========================================
  // GPUS
  // ==========================================
  {
    id: "gpu-gtx-1660-super",
    slug: "nvidia-geforce-gtx-1660-super-6gb",
    name: "NVIDIA GeForce GTX 1660 Super 6GB GDDR6",
    brand: "NVIDIA",
    model: "GTX 1660 Super",
    type: "GPU",
    benchmarkScore: 12800,
    bestPriceMyr: 370,
    bestNewPriceMyr: undefined,
    bestUsedPriceMyr: 370,
    hasUsedListings: true,
    inStock: true,
    specs: {
      chipBrand: "NVIDIA",
      vramGb: 6,
      lengthMm: 215,
      slotWidth: 2,
      tdpWattage: 125,
      recommendedPsuWattage: 450,
      powerConnectors: "1x 8-pin",
      has12Vhpwr: false,
    },
    marketPricing: {
      usedRange: { min: 340, max: 410, typical: 370 },
      fairTargetPriceMyr: 360,
      availability: "discontinued_used_only",
    },
    opinion: {
      verdict: "The sub-RM400 esports savior. Still effortlessly runs Dota 2, Valorant, GTA V, and Apex Legends at 1080p 60-120 FPS. Buy strictly second-hand.",
      recommendation: "must_buy_used",
      recommendationLabel: "Budget Esports Champion",
      pros: ["Sub-RM400 market pricing", "Compact size fits virtually any PC case", "Modest 125W draw runs on 450W power supplies"],
      cons: ["6GB VRAM limits modern AAA textures", "No hardware ray tracing or DLSS (FSR works)"],
      targetResolution: "1080p Budget",
      upgradeAdvice: "Check for clean fans and repaste with thermal compound upon purchase. Pair with any budget CPU from Ryzen 3600 to i3-12100F.",
      tierRanking: "B",
    },
  },
  {
    id: "gpu-rx-6600",
    slug: "amd-radeon-rx-6600-8gb",
    name: "AMD Radeon RX 6600 8GB GDDR6",
    brand: "AMD",
    model: "Radeon RX 6600",
    type: "GPU",
    benchmarkScore: 16500,
    bestPriceMyr: 540,
    bestNewPriceMyr: 899,
    bestUsedPriceMyr: 540,
    hasUsedListings: true,
    inStock: true,
    specs: {
      chipBrand: "AMD",
      vramGb: 8,
      lengthMm: 193,
      slotWidth: 2,
      tdpWattage: 132,
      recommendedPsuWattage: 450,
      powerConnectors: "1x 8-pin",
      has12Vhpwr: false,
    },
    marketPricing: {
      newRange: { min: 870, max: 940, typical: 899 },
      usedRange: { min: 510, max: 580, typical: 540 },
      fairTargetPriceMyr: 530,
      availability: "abundant",
    },
    opinion: {
      verdict: "The reigning king of Malaysian budget gaming. Demolishes the RTX 3050 and matches RTX 2060 Super performance while sipping only 130W of electricity.",
      recommendation: "must_buy_used",
      recommendationLabel: "King of 1080p Value",
      pros: ["Full 8GB VRAM buffer handles modern 1080p gaming", "Under RM550 used street price", "Tiny power consumption runs on standard 450W-500W PSUs"],
      cons: ["Weaker ray tracing acceleration than NVIDIA", "PCIe 4.0 x8 lane layout loses 2-4% on PCIe 3.0 motherboards"],
      targetResolution: "1080p High",
      upgradeAdvice: "The number one recommended upgrade for anyone with an older GTX 1050 Ti, GTX 1060, or RX 580.",
      tierRanking: "S",
    },
  },
  {
    id: "gpu-rtx-3060-12g",
    slug: "nvidia-geforce-rtx-3060-12gb",
    name: "NVIDIA GeForce RTX 3060 12GB GDDR6",
    brand: "NVIDIA",
    model: "RTX 3060 12GB",
    type: "GPU",
    benchmarkScore: 17200,
    bestPriceMyr: 780,
    bestNewPriceMyr: 1249,
    bestUsedPriceMyr: 780,
    hasUsedListings: true,
    inStock: true,
    specs: {
      chipBrand: "NVIDIA",
      vramGb: 12,
      lengthMm: 242,
      slotWidth: 2,
      tdpWattage: 170,
      recommendedPsuWattage: 550,
      powerConnectors: "1x 8-pin",
      has12Vhpwr: false,
    },
    marketPricing: {
      newRange: { min: 1200, max: 1320, typical: 1249 },
      usedRange: { min: 740, max: 840, typical: 780 },
      fairTargetPriceMyr: 770,
      availability: "abundant",
    },
    opinion: {
      verdict: "A modern classic that refuses to die. The generous 12GB VRAM buffer makes it an unbeatable sub-RM800 secondary market choice for Stable Diffusion AI and modded games.",
      recommendation: "must_buy_used",
      recommendationLabel: "Best Budget AI & Modding GPU",
      pros: ["12GB VRAM prevents texture stutter in newer 2024-2026 ports", "Superior local AI generation (CUDA) over AMD", "DLSS support prolongs playable lifespans"],
      cons: ["Pure rasterization is slightly slower than RX 6600 XT", "High new retail price (do not buy brand new)"],
      targetResolution: "1080p High",
      upgradeAdvice: "Buy used around RM750-800. Do not pay brand new retail (RM1,250+); for that budget look at RTX 4060 or used RX 6700 XT.",
      tierRanking: "A",
    },
  },
  {
    id: "gpu-rtx-4060",
    slug: "nvidia-geforce-rtx-4060-8gb",
    name: "NVIDIA GeForce RTX 4060 8GB GDDR6",
    brand: "NVIDIA",
    model: "RTX 4060",
    type: "GPU",
    benchmarkScore: 19800,
    bestPriceMyr: 1080,
    bestNewPriceMyr: 1389,
    bestUsedPriceMyr: 1080,
    hasUsedListings: true,
    inStock: true,
    specs: {
      chipBrand: "NVIDIA",
      vramGb: 8,
      lengthMm: 227,
      slotWidth: 2,
      tdpWattage: 115,
      recommendedPsuWattage: 500,
      powerConnectors: "1x 8-pin",
      has12Vhpwr: false,
    },
    marketPricing: {
      newRange: { min: 1350, max: 1460, typical: 1389 },
      usedRange: { min: 1040, max: 1150, typical: 1080 },
      fairTargetPriceMyr: 1050,
      availability: "abundant",
    },
    opinion: {
      verdict: "Flawless power efficiency (115W) with full access to DLSS 3 Frame Generation and AV1 encoding. Great for compact cases and warm tropical Malaysian climates.",
      recommendation: "safe_buy_new",
      recommendationLabel: "Ultra-Efficient 1080p Pick",
      pros: ["Incredible 115W power draw stays whisper quiet", "DLSS 3 Frame Generation multiplies frame rates", "Modern AV1 video encoder for streaming"],
      cons: ["8GB VRAM buffer limits maximum settings at 1440p", "128-bit memory bus bandwidth constraint"],
      targetResolution: "1080p High",
      upgradeAdvice: "If building brand-new with warranty, it is the safest mainstream NVIDIA choice. If you play at 1440p, consider saving for an RTX 4070 Super.",
      tierRanking: "A",
    },
  },
  {
    id: "gpu-rx-7800-xt",
    slug: "amd-radeon-rx-7800-xt-16gb",
    name: "AMD Radeon RX 7800 XT 16GB GDDR6",
    brand: "AMD",
    model: "Radeon RX 7800 XT",
    type: "GPU",
    benchmarkScore: 29500,
    bestPriceMyr: 1880,
    bestNewPriceMyr: 2399,
    bestUsedPriceMyr: 1880,
    hasUsedListings: true,
    inStock: true,
    specs: {
      chipBrand: "AMD",
      vramGb: 16,
      lengthMm: 280,
      slotWidth: 2.5,
      tdpWattage: 263,
      recommendedPsuWattage: 700,
      powerConnectors: "2x 8-pin",
      has12Vhpwr: false,
    },
    marketPricing: {
      newRange: { min: 2320, max: 2550, typical: 2399 },
      usedRange: { min: 1820, max: 1980, typical: 1880 },
      fairTargetPriceMyr: 1850,
      availability: "moderate",
    },
    opinion: {
      verdict: "The undisputed rasterization champion of 1440p gaming. Packs 16GB VRAM on a wide 256-bit bus, guaranteeing future-proof texture headroom without NVIDIA's pricing tax.",
      recommendation: "safe_buy_new",
      recommendationLabel: "Best 1440p Raw Value",
      pros: ["Massive 16GB VRAM never runs out of texture memory", "Beats RTX 4070 in pure rasterized frame rates", "No fragile 12VHPWR connector needed (standard 2x 8-pin)"],
      cons: ["Ray tracing falls behind RTX 4070 series", "Draws approximately 260W under full load"],
      targetResolution: "1440p Sweet Spot",
      upgradeAdvice: "Requires at least a certified 650W or 750W power supply. Perfect match for a 1440p 165Hz+ gaming monitor.",
      tierRanking: "S",
    },
  },
  {
    id: "gpu-rtx-4070-super",
    slug: "nvidia-geforce-rtx-4070-super-12gb",
    name: "NVIDIA GeForce RTX 4070 Super 12GB GDDR6X",
    brand: "NVIDIA",
    model: "RTX 4070 Super",
    type: "GPU",
    benchmarkScore: 31800,
    bestPriceMyr: 2380,
    bestNewPriceMyr: 2949,
    bestUsedPriceMyr: 2380,
    hasUsedListings: true,
    inStock: true,
    specs: {
      chipBrand: "NVIDIA",
      vramGb: 12,
      lengthMm: 242,
      slotWidth: 2,
      tdpWattage: 220,
      recommendedPsuWattage: 650,
      powerConnectors: "1x 16-pin 12VHPWR",
      has12Vhpwr: true,
    },
    marketPricing: {
      newRange: { min: 2850, max: 3150, typical: 2949 },
      usedRange: { min: 2300, max: 2500, typical: 2380 },
      fairTargetPriceMyr: 2350,
      availability: "moderate",
    },
    opinion: {
      verdict: "The gold standard 1440p gaming GPU. Comes with 20% more CUDA cores than the base 4070, matching previous-gen RTX 3090 speeds while consuming only 220W.",
      recommendation: "safe_buy_new",
      recommendationLabel: "The 1440p Gold Standard",
      pros: ["Matches RTX 3090 performance at nearly half the wattage", "Class-leading Ray Tracing and DLSS 3.5 Ray Reconstruction", "Fast GDDR6X memory"],
      cons: ["12GB VRAM is adequate for 1440p but modest for heavy 4K ray tracing", "Requires 12VHPWR adapter or ATX 3.0 PSU"],
      targetResolution: "1440p Sweet Spot",
      upgradeAdvice: "Pair with an ATX 3.0 power supply to avoid adapter clutter. Matches ideally with Ryzen 7 7800X3D or Core i5-13600KF.",
      tierRanking: "S",
    },
  },
  {
    id: "gpu-rtx-4080-super",
    slug: "nvidia-geforce-rtx-4080-super-16gb",
    name: "NVIDIA GeForce RTX 4080 Super 16GB GDDR6X",
    brand: "NVIDIA",
    model: "RTX 4080 Super",
    type: "GPU",
    benchmarkScore: 44500,
    bestPriceMyr: 3950,
    bestNewPriceMyr: 4899,
    bestUsedPriceMyr: 3950,
    hasUsedListings: true,
    inStock: true,
    specs: {
      chipBrand: "NVIDIA",
      vramGb: 16,
      lengthMm: 310,
      slotWidth: 3,
      tdpWattage: 320,
      recommendedPsuWattage: 750,
      powerConnectors: "1x 16-pin 12VHPWR",
      has12Vhpwr: true,
    },
    marketPricing: {
      newRange: { min: 4750, max: 5200, typical: 4899 },
      usedRange: { min: 3850, max: 4150, typical: 3950 },
      fairTargetPriceMyr: 3900,
      availability: "moderate",
    },
    opinion: {
      verdict: "High-end 4K luxury. Maxes out Cyberpunk 2077 with full Path Tracing at 4K using DLSS 3.5. Excellent workstation GPU for Blender, Maya, and local LLM inference.",
      recommendation: "enthusiast_tier",
      recommendationLabel: "High-End 4K Tier",
      pros: ["True 4K 100+ FPS capability in modern AAA titles", "Massive CUDA and Tensor processing power for local AI", "High resale retention in Malaysia"],
      cons: ["Large physical dimensions require roomy mid-tower case", "High initial financial commitment"],
      targetResolution: "4K Enthusiast",
      upgradeAdvice: "Ensure your PC case has at least 320mm GPU clearance and 850W ATX 3.0 Gold PSU.",
      tierRanking: "S",
    },
  },

  // ==========================================
  // MOTHERBOARDS
  // ==========================================
  {
    id: "mobo-b450m-hdv",
    slug: "asrock-b450m-hdv-r4-matx-am4",
    name: "ASRock B450M-HDV R4.0 Micro-ATX Motherboard",
    brand: "ASRock",
    model: "B450M-HDV R4.0",
    type: "MOTHERBOARD",
    benchmarkScore: 80,
    bestPriceMyr: 160,
    bestNewPriceMyr: 229,
    bestUsedPriceMyr: 160,
    hasUsedListings: true,
    inStock: true,
    specs: {
      socket: "AM4",
      chipset: "B450",
      formFactor: "Micro-ATX",
      ramType: "DDR4",
      ramSlots: 2,
      maxRamSpeedMhz: 3200,
      m2Slots: 1,
      sataPorts: 4,
      pcieGen: 3,
    },
    marketPricing: {
      newRange: { min: 210, max: 240, typical: 229 },
      usedRange: { min: 140, max: 180, typical: 160 },
      fairTargetPriceMyr: 155,
      availability: "abundant",
    },
    opinion: {
      verdict: "The ultimate survival budget AM4 motherboard. Barebones VRM without heatsinks, but easily powers Ryzen 5 3600 or 5600 for sub-RM1,800 builds.",
      recommendation: "must_buy_used",
      recommendationLabel: "Ultra-Budget Pick",
      pros: ["Cheapest viable AM4 motherboard on the market", "M.2 NVMe slot included", "Compact Micro-ATX footprint"],
      cons: ["No VRM heatsink (do not install Ryzen 7/9 chips)", "Only 2 RAM slots and PCIe 3.0 only"],
      targetResolution: "1080p Budget",
      upgradeAdvice: "Pair strictly with 65W CPUs like Ryzen 3600 or 5600. Avoid power-hungry 105W processors.",
      tierRanking: "C",
    },
  },
  {
    id: "mobo-b550m-vdh-wifi",
    slug: "msi-b550m-pro-vdh-wifi-am4-motherboard",
    name: "MSI B550M PRO-VDH WIFI Micro-ATX Motherboard",
    brand: "MSI",
    model: "B550M PRO-VDH WIFI",
    type: "MOTHERBOARD",
    benchmarkScore: 110,
    bestPriceMyr: 280,
    bestNewPriceMyr: 419,
    bestUsedPriceMyr: 280,
    hasUsedListings: true,
    inStock: true,
    specs: {
      socket: "AM4",
      chipset: "B550",
      formFactor: "Micro-ATX",
      ramType: "DDR4",
      ramSlots: 4,
      maxRamSpeedMhz: 4400,
      m2Slots: 2,
      sataPorts: 4,
      pcieGen: 4,
    },
    marketPricing: {
      newRange: { min: 400, max: 440, typical: 419 },
      usedRange: { min: 260, max: 310, typical: 280 },
      fairTargetPriceMyr: 275,
      availability: "abundant",
    },
    opinion: {
      verdict: "The definitive AM4 benchmark motherboard. Heatsinked VRMs, dual M.2 slots with PCIe 4.0 support, built-in WiFi, and 4 RAM slots at an accessible price.",
      recommendation: "must_buy_used",
      recommendationLabel: "Best Value AM4 Board",
      pros: ["Solid VRMs easily support Ryzen 5700X3D", "Dual M.2 SSD slots", "Built-in WiFi and Bluetooth"],
      cons: ["Secondary M.2 runs at PCIe 3.0 speeds", "No rear USB Type-C port"],
      targetResolution: "1080p High",
      upgradeAdvice: "The perfect foundation for Ryzen 5 5600 or Ryzen 7 5700X3D. BIOS flashback button allows easy CPU upgrades without an older chip.",
      tierRanking: "S",
    },
  },
  {
    id: "mobo-b650m-hdv",
    slug: "asrock-b650m-hdv-m2-am5-motherboard",
    name: "ASRock B650M-HDV/M.2 AM5 Micro-ATX Motherboard",
    brand: "ASRock",
    model: "B650M-HDV/M.2",
    type: "MOTHERBOARD",
    benchmarkScore: 125,
    bestPriceMyr: 420,
    bestNewPriceMyr: 549,
    bestUsedPriceMyr: 420,
    hasUsedListings: true,
    inStock: true,
    specs: {
      socket: "AM5",
      chipset: "B650",
      formFactor: "Micro-ATX",
      ramType: "DDR5",
      ramSlots: 2,
      maxRamSpeedMhz: 6400,
      m2Slots: 2,
      sataPorts: 4,
      pcieGen: 5,
    },
    marketPricing: {
      newRange: { min: 520, max: 570, typical: 549 },
      usedRange: { min: 400, max: 450, typical: 420 },
      fairTargetPriceMyr: 410,
      availability: "moderate",
    },
    opinion: {
      verdict: "The hardware community's favorite budget AM5 motherboard. Incredible 8+2+1 phase VRM with heavy heatsinks that can power even a Ryzen 9 without thermal throttling.",
      recommendation: "safe_buy_new",
      recommendationLabel: "Best Value AM5 Motherboard",
      pros: ["Top-tier VRMs for a budget board (handles Ryzen 7800X3D with ease)", "PCIe Gen5 M.2 SSD slot included", "Two-DIMM topology ensures stable memory overclocking"],
      cons: ["Only 2 RAM slots (install 32GB upfront)", "No integrated WiFi card included (has M.2 WiFi slot for upgrade)"],
      targetResolution: "1440p Sweet Spot",
      upgradeAdvice: "Combine with 32GB (2x16GB) DDR5 6000MHz CL30. Best pairing for Ryzen 7500F and 7800X3D.",
      tierRanking: "S",
    },
  },
  {
    id: "mobo-b760m-a-wifi",
    slug: "asus-prime-b760m-a-wifi-d4-lga1700",
    name: "ASUS PRIME B760M-A WIFI D4 LGA1700 Motherboard",
    brand: "ASUS",
    model: "PRIME B760M-A WIFI D4",
    type: "MOTHERBOARD",
    benchmarkScore: 115,
    bestPriceMyr: 360,
    bestNewPriceMyr: 549,
    bestUsedPriceMyr: 360,
    hasUsedListings: true,
    inStock: true,
    specs: {
      socket: "LGA1700",
      chipset: "B760",
      formFactor: "Micro-ATX",
      ramType: "DDR4",
      ramSlots: 4,
      maxRamSpeedMhz: 5333,
      m2Slots: 2,
      sataPorts: 4,
      pcieGen: 4,
    },
    marketPricing: {
      newRange: { min: 510, max: 570, typical: 549 },
      usedRange: { min: 340, max: 390, typical: 360 },
      fairTargetPriceMyr: 350,
      availability: "abundant",
    },
    opinion: {
      verdict: "Reliable Intel LGA1700 foundation that leverages inexpensive DDR4 RAM while supporting Intel 12th, 13th, and 14th Gen processors.",
      recommendation: "must_buy_used",
      recommendationLabel: "Intel DDR4 Mainstay",
      pros: ["DDR4 memory saves RM150 over DDR5 platforms", "Built-in WiFi 6 and Bluetooth", "Dual PCIe 4.0 M.2 slots"],
      cons: ["VRM heatsink is modest (avoid pairing with unlocked i7/i9 chips)", "LGA1700 platform has reached end of life"],
      targetResolution: "1080p High",
      upgradeAdvice: "Great pairing for Core i5-12400F or i5-13400F. Update BIOS immediately to ensure stable microcode voltage parameters.",
      tierRanking: "A",
    },
  },

  // ==========================================
  // RAM
  // ==========================================
  {
    id: "ram-fury-16gb-d4",
    slug: "kingston-fury-beast-16gb-2x8gb-ddr4-3200",
    name: "Kingston FURY Beast 16GB (2x8GB) DDR4-3200MHz CL16",
    brand: "Kingston",
    model: "FURY Beast DDR4",
    type: "RAM",
    benchmarkScore: 100,
    bestPriceMyr: 120,
    bestNewPriceMyr: 179,
    bestUsedPriceMyr: 120,
    hasUsedListings: true,
    inStock: true,
    specs: {
      ramType: "DDR4",
      capacityGb: 16,
      moduleCount: 2,
      speedMhz: 3200,
      casLatency: 16,
    },
    marketPricing: {
      newRange: { min: 165, max: 195, typical: 179 },
      usedRange: { min: 110, max: 135, typical: 120 },
      fairTargetPriceMyr: 115,
      availability: "abundant",
    },
    opinion: {
      verdict: "The standard baseline for budget gaming. Dual-channel 16GB at 3200MHz CL16 delivers smooth frametimes for almost all competitive esports titles.",
      recommendation: "must_buy_used",
      recommendationLabel: "Budget Standard",
      pros: ["Cheap and universally compatible", "Low profile heatsinks fit under any CPU cooler", "Low latency CL16"],
      cons: ["16GB is tight if you multitask heavily with Discord and Chrome open"],
      targetResolution: "1080p Budget",
      upgradeAdvice: "Install in memory slots A2 and B2 (slots 2 and 4) for proper dual-channel bandwidth. Enable XMP/DOCP in BIOS.",
      tierRanking: "A",
    },
  },
  {
    id: "ram-corsair-32gb-d4",
    slug: "corsair-vengeance-lpx-32gb-2x16gb-ddr4-3200",
    name: "Corsair Vengeance LPX 32GB (2x16GB) DDR4-3200MHz CL16",
    brand: "Corsair",
    model: "Vengeance LPX DDR4",
    type: "RAM",
    benchmarkScore: 120,
    bestPriceMyr: 210,
    bestNewPriceMyr: 309,
    bestUsedPriceMyr: 210,
    hasUsedListings: true,
    inStock: true,
    specs: {
      ramType: "DDR4",
      capacityGb: 32,
      moduleCount: 2,
      speedMhz: 3200,
      casLatency: 16,
    },
    marketPricing: {
      newRange: { min: 285, max: 325, typical: 309 },
      usedRange: { min: 195, max: 230, typical: 210 },
      fairTargetPriceMyr: 200,
      availability: "abundant",
    },
    opinion: {
      verdict: "The sweet spot capacity for AM4 or LGA1700 builders. 32GB completely eliminates memory paging stutters in memory-hungry titles like Cities Skylines, Hogwarts Legacy, and Microsoft Flight Simulator.",
      recommendation: "must_buy_used",
      recommendationLabel: "High Value AM4 Sweet Spot",
      pros: ["Zero memory bottlenecks when multitasking", "Low profile design avoids CPU cooler fan interference", "Solid build quality"],
      cons: ["DDR4 cannot be reused when upgrading to AM5"],
      targetResolution: "1440p Sweet Spot",
      upgradeAdvice: "Buy used around RM200 for immense value. Enables seamless background streaming, Discord, and browsing.",
      tierRanking: "S",
    },
  },
  {
    id: "ram-gskill-32gb-d5",
    slug: "gskill-ripjaws-s5-32gb-2x16gb-ddr5-6000-cl30",
    name: "G.Skill Flare X5 32GB (2x16GB) DDR5-6000MHz CL30 AMD EXPO",
    brand: "G.Skill",
    model: "Flare X5 DDR5",
    type: "RAM",
    benchmarkScore: 160,
    bestPriceMyr: 380,
    bestNewPriceMyr: 489,
    bestUsedPriceMyr: 380,
    hasUsedListings: true,
    inStock: true,
    specs: {
      ramType: "DDR5",
      capacityGb: 32,
      moduleCount: 2,
      speedMhz: 6000,
      casLatency: 30,
    },
    marketPricing: {
      newRange: { min: 460, max: 510, typical: 489 },
      usedRange: { min: 360, max: 410, typical: 380 },
      fairTargetPriceMyr: 375,
      availability: "moderate",
    },
    opinion: {
      verdict: "The mathematical sweet spot for AMD AM5 processors. 6000MHz speed aligns perfectly with the 1:1 Infinity Fabric clock, and ultra-tight CL30 timing yields minimum latency.",
      recommendation: "safe_buy_new",
      recommendationLabel: "AM5 Sweet Spot Pick",
      pros: ["Tight CL30 latency boosts gaming minimum 1% lows", "Pre-configured AMD EXPO profile for one-click stability", "High-binned SK Hynix memory chips"],
      cons: ["Premium price over loose CL36/CL40 kits"],
      targetResolution: "1440p Sweet Spot",
      upgradeAdvice: "Always prioritize 6000MHz CL30 over 6400MHz or higher for AM5 to maintain stable 1:1 memory controller synchronization.",
      tierRanking: "S",
    },
  },

  // ==========================================
  // STORAGE
  // ==========================================
  {
    id: "ssd-kingston-nv2-1tb",
    slug: "kingston-nv2-1tb-pcie-4-nvme-ssd",
    name: "Kingston NV2 1TB PCIe 4.0 NVMe M.2 SSD",
    brand: "Kingston",
    model: "NV2 1TB",
    type: "STORAGE",
    benchmarkScore: 3500,
    bestPriceMyr: 259,
    bestNewPriceMyr: 259,
    bestUsedPriceMyr: undefined,
    hasUsedListings: false,
    inStock: true,
    specs: {
      formFactor: "M.2 2280",
      interface: "NVMe PCIe 4.0",
      capacityGb: 1000,
      readSpeedMbps: 3500,
    },
    marketPricing: {
      newRange: { min: 240, max: 275, typical: 259 },
      fairTargetPriceMyr: 250,
      availability: "abundant",
    },
    opinion: {
      verdict: "Malaysia's most popular budget NVMe drive. QLC flash without DRAM cache, but load times in games are practically indistinguishable from high-end drives.",
      recommendation: "safe_buy_new",
      recommendationLabel: "Buy New for Warranty",
      pros: ["Sub-RM260 for a full 1TB NVMe drive", "PCIe 4.0 interface", "3-year official warranty"],
      cons: ["DRAM-less design slows down during continuous 100GB+ file transfers", "Never buy used due to unknown write wear"],
      targetResolution: "1080p High",
      upgradeAdvice: "Always buy storage brand new. Secondary market SSDs often carry degraded NAND write endurance (TBW) and lack warranty coverage.",
      tierRanking: "B",
    },
  },
  {
    id: "ssd-lexar-nm790-2tb",
    slug: "lexar-nm790-2tb-pcie-4-nvme-ssd",
    name: "Lexar NM790 2TB High-Speed PCIe 4.0 NVMe M.2 SSD",
    brand: "Lexar",
    model: "NM790 2TB",
    type: "STORAGE",
    benchmarkScore: 7400,
    bestPriceMyr: 589,
    bestNewPriceMyr: 589,
    bestUsedPriceMyr: undefined,
    hasUsedListings: false,
    inStock: true,
    specs: {
      formFactor: "M.2 2280",
      interface: "NVMe PCIe 4.0",
      capacityGb: 2000,
      readSpeedMbps: 7400,
    },
    marketPricing: {
      newRange: { min: 560, max: 620, typical: 589 },
      fairTargetPriceMyr: 580,
      availability: "moderate",
    },
    opinion: {
      verdict: "Maxi-performance Gen4 drive. Maxes out the PCIe 4.0 bus at 7,400 MB/s using premium 3D TLC NAND. Runs remarkably cool and delivers PS5 / high-end PC performance.",
      recommendation: "safe_buy_new",
      recommendationLabel: "High Performance Gen4 Pick",
      pros: ["Blazing 7,400 MB/s read speeds", "High endurance TLC NAND (1500 TBW)", "Extremely cool running operation"],
      cons: ["Higher upfront cost than entry drives"],
      targetResolution: "4K Enthusiast",
      upgradeAdvice: "The recommended 2TB drive for high-end builds. 5-year warranty ensures long-term peace of mind.",
      tierRanking: "S",
    },
  },

  // ==========================================
  // POWER SUPPLIES (PSUS)
  // ==========================================
  {
    id: "psu-msi-a550bn",
    slug: "msi-mag-a550bn-550w-80-plus-bronze",
    name: "MSI MAG A550BN 550W 80+ Bronze Power Supply",
    brand: "MSI",
    model: "MAG A550BN",
    type: "PSU",
    benchmarkScore: 550,
    bestPriceMyr: 209,
    bestNewPriceMyr: 209,
    bestUsedPriceMyr: undefined,
    hasUsedListings: false,
    inStock: true,
    specs: {
      wattage: 550,
      efficiencyRating: "80+ Bronze",
      formFactor: "ATX",
      modularity: "Non",
      has12Vhpwr: false,
    },
    marketPricing: {
      newRange: { min: 195, max: 220, typical: 209 },
      fairTargetPriceMyr: 205,
      availability: "abundant",
    },
    opinion: {
      verdict: "The gold standard budget PSU on the Cultists Tier List (Tier C). Features modern DC-to-DC topology and full safety protections (OVP, OCP, SCP). Never gamble on unbranded power supplies.",
      recommendation: "safe_buy_new",
      recommendationLabel: "Must Buy Brand New",
      pros: ["DC-to-DC converter topology for tight voltage regulation", "Cultists Tier C verified reliability", "5-year local distributor warranty"],
      cons: ["Non-modular cables require careful cable tucking", "No 12VHPWR connector"],
      targetResolution: "1080p High",
      upgradeAdvice: "Strict rule: NEVER purchase used power supplies. Capacitors degrade over time, and a failing PSU can destroy every connected component.",
      tierRanking: "A",
    },
  },
  {
    id: "psu-coolermaster-mwe-650",
    slug: "cooler-master-mwe-650-bronze-v2",
    name: "Cooler Master MWE Bronze 650W V2 80+ Bronze Power Supply",
    brand: "Cooler Master",
    model: "MWE 650 Bronze V2",
    type: "PSU",
    benchmarkScore: 650,
    bestPriceMyr: 269,
    bestNewPriceMyr: 269,
    bestUsedPriceMyr: undefined,
    hasUsedListings: false,
    inStock: true,
    specs: {
      wattage: 650,
      efficiencyRating: "80+ Bronze",
      formFactor: "ATX",
      modularity: "Non",
      has12Vhpwr: false,
    },
    marketPricing: {
      newRange: { min: 255, max: 285, typical: 269 },
      fairTargetPriceMyr: 265,
      availability: "abundant",
    },
    opinion: {
      verdict: "High-value 650W PSU with 80+ Bronze certification. Plenty of headroom for mid-range GPUs like RTX 4060 Ti, RX 6700 XT, or RX 7600 XT.",
      recommendation: "safe_buy_new",
      recommendationLabel: "Must Buy Brand New",
      pros: ["Solid 650W continuous power delivery", "Quiet fan profile with HDB bearing", "5-year warranty"],
      cons: ["Non-modular black ribbon cables"],
      targetResolution: "1440p Sweet Spot",
      upgradeAdvice: "Always buy power supplies brand new with full local distributor warranty coverage.",
      tierRanking: "A",
    },
  },
  {
    id: "psu-corsair-rm750e",
    slug: "corsair-rm750e-750w-80-plus-gold-atx3",
    name: "Corsair RM750e 750W 80+ Gold Fully Modular ATX 3.0",
    brand: "Corsair",
    model: "RM750e (2023)",
    type: "PSU",
    benchmarkScore: 750,
    bestPriceMyr: 479,
    bestNewPriceMyr: 479,
    bestUsedPriceMyr: undefined,
    hasUsedListings: false,
    inStock: true,
    specs: {
      wattage: 750,
      efficiencyRating: "80+ Gold",
      formFactor: "ATX",
      modularity: "Full",
      has12Vhpwr: true,
    },
    marketPricing: {
      newRange: { min: 460, max: 510, typical: 479 },
      fairTargetPriceMyr: 470,
      availability: "moderate",
    },
    opinion: {
      verdict: "Modern ATX 3.0 and PCIe 5.0 ready PSU. Includes native 12VHPWR cable to power RTX 4070 series cards without messy multi-cable adapters. Fully modular design.",
      recommendation: "safe_buy_new",
      recommendationLabel: "ATX 3.0 Sweet Spot",
      pros: ["Native 12VHPWR 16-pin cable included", "80+ Gold high efficiency saves power", "Fully modular cables for clean aesthetics"],
      cons: ["Slightly smaller 120mm fan than standard RMx series"],
      targetResolution: "1440p Sweet Spot",
      upgradeAdvice: "Mandatory foundation when building with RTX 4070 Super or RTX 4070 Ti Super graphics cards.",
      tierRanking: "S",
    },
  },
  {
    id: "psu-seasonic-focus-850",
    slug: "seasonic-focus-gx-850-850w-80-plus-gold-atx3",
    name: "Seasonic FOCUS GX-850 850W 80+ Gold Fully Modular ATX 3.0",
    brand: "Seasonic",
    model: "FOCUS GX-850 ATX 3.0",
    type: "PSU",
    benchmarkScore: 850,
    bestPriceMyr: 649,
    bestNewPriceMyr: 649,
    bestUsedPriceMyr: undefined,
    hasUsedListings: false,
    inStock: true,
    specs: {
      wattage: 850,
      efficiencyRating: "80+ Gold",
      formFactor: "ATX",
      modularity: "Full",
      has12Vhpwr: true,
    },
    marketPricing: {
      newRange: { min: 620, max: 680, typical: 649 },
      fairTargetPriceMyr: 640,
      availability: "moderate",
    },
    opinion: {
      verdict: "Tier A+ build quality backed by an industry-leading 10-year warranty. Full Japanese 105C capacitors and hybrid fanless mode.",
      recommendation: "safe_buy_new",
      recommendationLabel: "Long-Term Investment",
      pros: ["10-year manufacturer warranty", "100% Japanese 105C electrolytic capacitors", "Handles high transient power spikes up to 200%"],
      cons: ["Premium price point"],
      targetResolution: "4K Enthusiast",
      upgradeAdvice: "Buy once and keep for the next 2-3 full PC builds. Easily powers RTX 4080 Super and flagship CPUs.",
      tierRanking: "S",
    },
  },

  // ==========================================
  // CASES
  // ==========================================
  {
    id: "case-tecware-forge-m",
    slug: "tecware-forge-m-argb-matx-case",
    name: "Tecware Forge M ARGB High Airflow Micro-ATX Case",
    brand: "Tecware",
    model: "Forge M ARGB",
    type: "CASE",
    benchmarkScore: 100,
    bestPriceMyr: 159,
    bestNewPriceMyr: 159,
    bestUsedPriceMyr: 100,
    hasUsedListings: true,
    inStock: true,
    specs: {
      formFactorSupport: ["Micro-ATX", "Mini-ITX"],
      maxGpuLengthMm: 340,
      maxCpuCoolerHeightMm: 160,
      maxPsuLengthMm: 180,
    },
    marketPricing: {
      newRange: { min: 149, max: 175, typical: 159 },
      usedRange: { min: 90, max: 120, typical: 100 },
      fairTargetPriceMyr: 150,
      availability: "abundant",
    },
    opinion: {
      verdict: "Malaysia's favorite high-airflow budget chassis. Ships with 4 pre-installed ARGB fans, full mesh front panel, and tempered glass side panel for only RM159.",
      recommendation: "safe_buy_new",
      recommendationLabel: "Budget Airflow King",
      pros: ["4x pre-installed ARGB fans save RM60+", "Full mesh front panel ensures cool tropical temps", "Supports long 340mm GPUs"],
      cons: ["Micro-ATX or ITX boards only (does not fit standard ATX)", "Thinner steel gauge than premium cases"],
      targetResolution: "1080p High",
      upgradeAdvice: "Great value buy new since it includes all fans upfront. Clean dust filters every 2 months in Malaysian households.",
      tierRanking: "S",
    },
  },
  {
    id: "case-montech-air-903",
    slug: "montech-air-903-max-atx-case",
    name: "Montech AIR 903 MAX Mesh High-Airflow ATX Case",
    brand: "Montech",
    model: "AIR 903 MAX",
    type: "CASE",
    benchmarkScore: 120,
    bestPriceMyr: 279,
    bestNewPriceMyr: 279,
    bestUsedPriceMyr: 180,
    hasUsedListings: true,
    inStock: true,
    specs: {
      formFactorSupport: ["ATX", "Micro-ATX", "Mini-ITX"],
      maxGpuLengthMm: 400,
      maxCpuCoolerHeightMm: 180,
      maxPsuLengthMm: 240,
    },
    marketPricing: {
      newRange: { min: 265, max: 299, typical: 279 },
      usedRange: { min: 170, max: 210, typical: 180 },
      fairTargetPriceMyr: 270,
      availability: "abundant",
    },
    opinion: {
      verdict: "Class-leading mid-tower airflow. Pre-installed with four massive 140mm PWM fans (3 ARGB + 1 rear) and fits even the largest RTX 4090 cards without clearance issues.",
      recommendation: "safe_buy_new",
      recommendationLabel: "Best Mid-Tower Overall",
      pros: ["Four 140mm PWM fans move colossal amounts of air quietly", "Supports up to 400mm GPU length", "Front USB Type-C port included"],
      cons: ["Wide physical footprint"],
      targetResolution: "1440p Sweet Spot",
      upgradeAdvice: "The best all-round mid-tower chassis for modern gaming and workstation builds.",
      tierRanking: "S",
    },
  },
  {
    id: "case-nr200",
    slug: "cooler-master-masterbox-nr200-itx-case",
    name: "Cooler Master MasterBox NR200 Mini-ITX SFF Case",
    brand: "Cooler Master",
    model: "MasterBox NR200",
    type: "CASE",
    benchmarkScore: 110,
    bestPriceMyr: 220,
    bestNewPriceMyr: 319,
    bestUsedPriceMyr: 220,
    hasUsedListings: true,
    inStock: true,
    specs: {
      formFactorSupport: ["Mini-ITX"],
      maxGpuLengthMm: 330,
      maxCpuCoolerHeightMm: 155,
      maxPsuLengthMm: 130,
    },
    marketPricing: {
      newRange: { min: 299, max: 340, typical: 319 },
      usedRange: { min: 200, max: 240, typical: 220 },
      fairTargetPriceMyr: 215,
      availability: "moderate",
    },
    opinion: {
      verdict: "The gateway drug to Small Form Factor (SFF) PC building. At 18 liters, it accommodates triple-slot GPUs and standard air coolers without complex watercooling requirements.",
      recommendation: "must_buy_used",
      recommendationLabel: "SFF Compact Favorite",
      pros: ["True compact 18L desk footprint", "Fits triple-slot 330mm graphics cards", "Exceptional panel ventilation"],
      cons: ["Requires SFX or SFX-L power supply", "Mini-ITX motherboards only"],
      targetResolution: "1440p Sweet Spot",
      upgradeAdvice: "Abundant on the Malaysian second-hand market (Carousell/Lowyat) around RM200-220.",
      tierRanking: "A",
    },
  },

  // ==========================================
  // COOLERS
  // ==========================================
  {
    id: "cooler-deepcool-ak400",
    slug: "deepcool-ak400-single-tower-cpu-cooler",
    name: "DeepCool AK400 High Performance Single Tower Air Cooler",
    brand: "DeepCool",
    model: "AK400",
    type: "COOLER",
    benchmarkScore: 220,
    bestPriceMyr: 65,
    bestNewPriceMyr: 115,
    bestUsedPriceMyr: 65,
    hasUsedListings: true,
    inStock: true,
    specs: {
      coolerType: "Air",
      supportedSockets: ["AM4", "AM5", "LGA1700", "LGA1851"],
      heightMm: 155,
      maxTdpWattage: 220,
    },
    marketPricing: {
      newRange: { min: 105, max: 125, typical: 115 },
      usedRange: { min: 60, max: 75, typical: 65 },
      fairTargetPriceMyr: 65,
      availability: "abundant",
    },
    opinion: {
      verdict: "Crisp matrix fin design with 4 direct-touch copper heatpipes. Keeps 65W chips like Ryzen 5600, 7500F, and i5-12400F under 65C in Malaysian 32C ambient room temperatures.",
      recommendation: "must_buy_used",
      recommendationLabel: "Budget Air Cooler Pick",
      pros: ["Whisper quiet FDB fan", "Zero RAM clearance interference", "Sub-RM70 on used market"],
      cons: ["Not designed for high-wattage 180W+ Intel unlocked chips"],
      targetResolution: "1080p High",
      upgradeAdvice: "Buy used or new. Easy installation with pre-applied thermal paste on new retail units.",
      tierRanking: "S",
    },
  },
  {
    id: "cooler-thermalright-pa120",
    slug: "thermalright-peerless-assassin-120-se-argb",
    name: "Thermalright Peerless Assassin 120 SE ARGB Dual Tower Cooler",
    brand: "Thermalright",
    model: "Peerless Assassin 120 SE",
    type: "COOLER",
    benchmarkScore: 245,
    bestPriceMyr: 110,
    bestNewPriceMyr: 159,
    bestUsedPriceMyr: 110,
    hasUsedListings: true,
    inStock: true,
    specs: {
      coolerType: "Air",
      supportedSockets: ["AM4", "AM5", "LGA1700", "LGA1851"],
      heightMm: 155,
      maxTdpWattage: 245,
    },
    marketPricing: {
      newRange: { min: 145, max: 170, typical: 159 },
      usedRange: { min: 100, max: 125, typical: 110 },
      fairTargetPriceMyr: 110,
      availability: "abundant",
    },
    opinion: {
      verdict: "The cooler that shook the entire hardware industry. Six heatpipes, dual heatsink towers, and dual PWM fans matching RM400 Noctua coolers for only RM159 new.",
      recommendation: "safe_buy_new",
      recommendationLabel: "Greatest Cooler Value in History",
      pros: ["Cools 200W+ heat loads effortlessly", "Beats many 240mm liquid AIO coolers", "Zero pump failure risk"],
      cons: ["Front fan may need slight elevation over tall RGB RAM sticks"],
      targetResolution: "1440p Sweet Spot",
      upgradeAdvice: "The definitive cooler choice for Ryzen 5700X3D, 7800X3D, or Core i5-13600K. Buy new at RM159 or used around RM110.",
      tierRanking: "S",
    },
  },
  {
    id: "cooler-thermalright-aqua-360",
    slug: "thermalright-aqua-elite-360-v3-argb-aio",
    name: "Thermalright Aqua Elite 360 V3 ARGB 360mm Liquid Cooler",
    brand: "Thermalright",
    model: "Aqua Elite 360 V3",
    type: "COOLER",
    benchmarkScore: 300,
    bestPriceMyr: 220,
    bestNewPriceMyr: 289,
    bestUsedPriceMyr: 220,
    hasUsedListings: true,
    inStock: true,
    specs: {
      coolerType: "AIO 360",
      supportedSockets: ["AM4", "AM5", "LGA1700", "LGA1851"],
      heightMm: 52,
      maxTdpWattage: 300,
    },
    marketPricing: {
      newRange: { min: 275, max: 310, typical: 289 },
      usedRange: { min: 200, max: 240, typical: 220 },
      fairTargetPriceMyr: 220,
      availability: "moderate",
    },
    opinion: {
      verdict: "Full 360mm liquid cooling performance under RM300. Features a modern low-vibration pump, braided tubing, and 3 high-static pressure ARGB fans.",
      recommendation: "safe_buy_new",
      recommendationLabel: "Budget Liquid 360mm Pick",
      pros: ["Sub-RM300 for a 360mm radiator", "Keeps high-core CPUs cool and quiet", "Clean modern aesthetics"],
      cons: ["Requires case with 360mm radiator mounting support", "AIO pumps have a typical 4-6 year lifespan"],
      targetResolution: "Workstation / Production",
      upgradeAdvice: "Ensure your PC case supports 360mm top or front radiator mounting before purchasing.",
      tierRanking: "A",
    },
  },
];

function generateQuotesForPart(p: any): RetailerQuote[] {
  const quotes: RetailerQuote[] = [];
  if (p.bestNewPriceMyr || p.marketPricing?.newRange) {
    const price = p.bestNewPriceMyr || p.marketPricing?.newRange?.min || p.bestPriceMyr;
    quotes.push({
      retailerId: "ret-shopee",
      retailerName: "Shopee MY (Retail Mall)",
      retailerSlug: "shopee-my",
      priceMyr: price,
      condition: "new",
      sellerLocation: "Kuala Lumpur",
      listingTitle: `${p.name} Brand New Sealed`,
      isMarketplace: false,
      inStock: true,
      productUrl: "#",
      lastScrapedAt: new Date().toISOString(),
    });
    quotes.push({
      retailerId: "ret-lowyat",
      retailerName: "Lowyat Plaza Retailer",
      retailerSlug: "lowyat-retail",
      priceMyr: (p.marketPricing?.newRange?.typical || price) + 15,
      condition: "new",
      sellerLocation: "Kuala Lumpur",
      listingTitle: `${p.name} Local Stock`,
      isMarketplace: false,
      inStock: true,
      productUrl: "#",
      lastScrapedAt: new Date().toISOString(),
    });
  }
  if (p.hasUsedListings || p.bestUsedPriceMyr || p.marketPricing?.usedRange) {
    const usedPrice = p.bestUsedPriceMyr || p.marketPricing?.usedRange?.min || p.bestPriceMyr;
    quotes.push({
      retailerId: "ret-carousell",
      retailerName: "Carousell MY",
      retailerSlug: "carousell-my",
      priceMyr: usedPrice,
      condition: "used_good",
      sellerLocation: "Petaling Jaya, Selangor",
      listingTitle: `${p.name} (Tested Working)`,
      isMarketplace: true,
      inStock: true,
      productUrl: "#",
      lastScrapedAt: new Date().toISOString(),
    });
    quotes.push({
      retailerId: "ret-mudah",
      retailerName: "Mudah.my",
      retailerSlug: "mudah-my",
      priceMyr: (p.marketPricing?.usedRange?.typical || usedPrice) + 20,
      condition: "used_good",
      sellerLocation: "Subang Jaya, Selangor",
      listingTitle: `${p.name} Pre-owned`,
      isMarketplace: true,
      inStock: true,
      productUrl: "#",
      lastScrapedAt: new Date().toISOString(),
    });
  }
  return quotes;
}

export const SEED_PARTS: PartItem[] = RAW_SEED_PARTS.map((p) => ({
  ...p,
  prices: generateQuotesForPart(p),
}));

