export type TipCategory = "pc-tips" | "cool-tools" | "fun-stuff";

export interface TipItem {
  id: string;
  category: TipCategory;
  title: string;
  titleMs: string;
  badge: string;
  badgeColor: string;
  summary: string;
  summaryMs: string;
  commandOrAction?: string;
  isCommand?: boolean;
  officialUrl?: string;
  githubUrl?: string;
  developer?: string;
  details?: string;
  detailsMs?: string;
  safetyNote?: string;
  safetyNoteMs?: string;
  tags: string[];
}

export const TIPS_CATEGORIES = [
  { id: "all", label: "All Items", labelMs: "Semua" },
  { id: "pc-tips", label: "PC Tips & Terminal", labelMs: "Tips PC & Terminal" },
  { id: "cool-tools", label: "Cool Tools & Debloaters", labelMs: "Alatan & Debloater" },
  { id: "fun-stuff", label: "Fun Stuff & Easter Eggs", labelMs: "Easter Egg & Rahsia" },
] as const;

export const TIPS_DATA: TipItem[] = [
  // ==========================================
  // 1. PC TIPS (CMD, POWERSHELL, OS TRICKS)
  // ==========================================
  {
    id: "tip-winget-upgrade",
    category: "pc-tips",
    title: "Mass Package Updater",
    titleMs: "Kemaskini Semua Perisian Sekaligus",
    badge: "Package Manager",
    badgeColor: "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/20",
    summary: "Upgrades all installed applications that have newer versions in the Windows Package Manager.",
    summaryMs: "Kemaskini semua aplikasi yang dipasang dalam satu arahan pantas.",
    commandOrAction: "winget upgrade --all --include-unknown",
    isCommand: true,
    details: "Runs an unattended upgrade loop across browsers, developer runtimes, and desktop utilities without manual installer downloads.",
    detailsMs: "Menjalankan proses kemaskini untuk pelayar web, runtime, dan aplikasi tanpa muat turun manual.",
    tags: ["winget", "update", "terminal", "powershell", "cmd", "apps"],
  },
  {
    id: "tip-powercfg-battery",
    category: "pc-tips",
    title: "Battery Health & Degradation Audit",
    titleMs: "Audit Kesihatan & Kerosakan Bateri",
    badge: "Hardware Telemetry",
    badgeColor: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20",
    summary: "Generates an HTML diagnostic report with factory design capacity, current max capacity, and cycle count.",
    summaryMs: "Menghasilkan laporan HTML terperinci mengenai kapasiti asal, kapasiti semasa, dan kitaran caj bateri.",
    commandOrAction: 'powercfg /batteryreport /output "%USERPROFILE%\\Desktop\\battery-report.html"',
    isCommand: true,
    details: "Compares Design Capacity vs Full Charge Capacity to pinpoint physical cell degradation and unexpected shutdowns.",
    detailsMs: "Membandingkan kapasiti kilang dengan kapasiti semasa untuk mengukur kehausan bateri laptop.",
    tags: ["battery", "laptop", "powercfg", "hardware", "diagnostic"],
  },
  {
    id: "tip-dism-restorehealth",
    category: "pc-tips",
    title: "DISM Component Store Repair",
    titleMs: "Pembaikan Component Store DISM",
    badge: "System Integrity",
    badgeColor: "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20",
    summary: "Scans and repairs corrupted Windows component store (WinSxS) files using official Windows Update servers.",
    summaryMs: "Memeriksa dan membaiki fail WinSxS Windows yang rosak terus dari pelayan Windows Update.",
    commandOrAction: "DISM /Online /Cleanup-Image /RestoreHealth",
    isCommand: true,
    details: "Must be run prior to SFC when the local backup payload itself is damaged. Solves persistent update error loops.",
    detailsMs: "Dijalankan sebelum sfc /scannow jika arkib tempatan rosak. Membaiki ralat kemaskini Windows.",
    tags: ["dism", "repair", "windows update", "cmd", "admin"],
  },
  {
    id: "tip-sfc-scannow",
    category: "pc-tips",
    title: "System File Integrity Check",
    titleMs: "Pemeriksaan Integriti Fail Sistem",
    badge: "First Aid",
    badgeColor: "bg-rose-500/10 text-rose-600 dark:text-rose-400 border-rose-500/20",
    summary: "Scans all protected Windows operating system files and replaces corrupted binaries with clean cached copies.",
    summaryMs: "Memeriksa fail sistem terlindung dan menggantikan fail rosak dengan salinan bersih.",
    commandOrAction: "sfc /scannow",
    isCommand: true,
    details: "Essential first-line fix after unexpected power losses, blue screens, or missing system DLL errors.",
    detailsMs: "Langkah pertama wajib selepas insiden blackout, blue screen, atau fail DLL hilang.",
    tags: ["sfc", "repair", "crash", "dll", "integrity"],
  },
  {
    id: "tip-robocopy-multithread",
    category: "pc-tips",
    title: "Multi-Threaded Resilient File Replication",
    titleMs: "Salin Fail Pantas & Kalis Terputus",
    badge: "File Management",
    badgeColor: "bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-500/20",
    summary: "Copies directories with 16 parallel threads, retains file permissions, and resumes interrupted transfers.",
    summaryMs: "Menyalin direktori dengan 16 thread serentak tanpa tersangkut pada fail terkunci.",
    commandOrAction: 'robocopy "C:\\Source" "D:\\Destination" /E /ZB /MT:16 /R:1 /W:1 /V',
    isCommand: true,
    details: "Bypasses File Explorer stall-outs on deep path structures and permission blocks using backup operator mode (/ZB).",
    detailsMs: "Mengelakkan masalah File Explorer tergantung ketika memindahkan fail bersaiz besar atau banyak folder.",
    tags: ["robocopy", "backup", "files", "transfer", "speed"],
  },
  {
    id: "tip-wifi-password",
    category: "pc-tips",
    title: "Clear-Text Wi-Fi Password Extraction",
    titleMs: "Dapatkan Kata Laluan Wi-Fi Tersimpan",
    badge: "Networking",
    badgeColor: "bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 border-cyan-500/20",
    summary: "Displays saved network profile security key in plain text without logging into router settings.",
    summaryMs: "Memaparkan kata laluan Wi-Fi tersimpan dalam teks jelas tanpa buka tetapan router.",
    commandOrAction: 'netsh wlan show profile name="SSID_NAME" key=clear',
    isCommand: true,
    details: "Replace SSID_NAME with your network name. Look for 'Key Content' under the Security settings section.",
    detailsMs: "Gantikan SSID_NAME dengan nama Wi-Fi anda. Lihat pada bahagian 'Key Content'.",
    tags: ["wifi", "password", "netsh", "network", "cmd"],
  },
  {
    id: "tip-cold-shutdown",
    category: "pc-tips",
    title: "True Cold Kernel Shutdown",
    titleMs: "Tutup PC Sepenuhnya (Zero-Power)",
    badge: "Power Management",
    badgeColor: "bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border-indigo-500/20",
    summary: "Kills all active applications immediately and forces a true zero-power cold reboot without Fast Startup hibernation.",
    summaryMs: "Menutup semua aplikasi serta-merta dan mematikan kernel tanpa Fast Startup.",
    commandOrAction: "shutdown /s /f /t 0",
    isCommand: true,
    details: "Flushes hung kernel drivers and clears volatile memory allocations that persist through normal Windows 10/11 hybrid shutdowns.",
    detailsMs: "Membersihkan driver yang sangkut dan membuang memori sementara yang terperangkap dalam Fast Startup.",
    tags: ["shutdown", "power", "fast startup", "clean", "kernel"],
  },
  {
    id: "tip-clipboard-history",
    category: "pc-tips",
    title: "Extended Multi-Item Clipboard History",
    titleMs: "Sejarah Papan Keratan (Clipboard History)",
    badge: "Productivity",
    badgeColor: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20",
    summary: "Opens a floating clipboard menu with your last 25 copied text snippets, screenshots, and pinned favorites.",
    summaryMs: "Membuka menu terapung 25 teks dan screenshot terakhir yang disalin dengan fungsi pin.",
    commandOrAction: "Win + V",
    isCommand: false,
    details: "Enable in Settings > System > Clipboard. Supports pinning boilerplate text and license keys across computer restarts.",
    detailsMs: "Aktifkan dalam Tetapan > Sistem > Papan Keratan. Boleh pin teks penting walaupun selepas restart.",
    tags: ["clipboard", "hotkey", "windows", "productivity"],
  },
  {
    id: "tip-god-mode",
    category: "pc-tips",
    title: "God Mode Centralized Control Panel",
    titleMs: "Folder God Mode Semua Tetapan",
    badge: "Admin Access",
    badgeColor: "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20",
    summary: "Creates a master folder linking over 200 legacy Control Panel applets and administrative settings into one searchable view.",
    summaryMs: "Mencipta folder khas yang mengumpulkan lebih 200 tetapan kawalan Windows dalam satu senarai.",
    commandOrAction: "GodMode.{ED7BA470-8E54-465E-825C-99712043E01C}",
    isCommand: false,
    details: "Create a new folder on Desktop or in Explorer, paste this exact string as the folder name, and press Enter.",
    detailsMs: "Cipta folder baharu di Desktop, namakan dengan kod di atas dan tekan Enter.",
    tags: ["god mode", "control panel", "admin", "folder", "settings"],
  },
  {
    id: "tip-classic-context-menu",
    category: "pc-tips",
    title: "Restore Classic Windows 10 Context Menu in Win 11",
    titleMs: "Kembalikan Menu Klik Kanan Klasik Win 10",
    badge: "UI Tweak",
    badgeColor: "bg-sky-500/10 text-sky-600 dark:text-sky-400 border-sky-500/20",
    summary: "Bypasses the truncated Windows 11 right-click menu and eliminates the 'Show more options' click permanently.",
    summaryMs: "Kembalikan menu klik kanan penuh Windows 10 tanpa perlu tekan 'Show more options'.",
    commandOrAction: 'reg add "HKCU\\Software\\Classes\\CLSID\\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\\InprocServer32" /f /ve && taskkill /f /im explorer.exe && start explorer.exe',
    isCommand: true,
    details: "Adds a user-level registry override. Easily reversible anytime with reg delete on the same key.",
    detailsMs: "Menambah kunci pendaftaran peringkat pengguna. Boleh dipadam bila-bila masa jika mahu menu asal.",
    tags: ["context menu", "windows 11", "registry", "ui", "explorer"],
  },
  {
    id: "tip-sleep-blockers",
    category: "pc-tips",
    title: "Find Processes Preventing PC Sleep",
    titleMs: "Kesan Aplikasi Yang Halang PC Tidur",
    badge: "Power Diagnostics",
    badgeColor: "bg-rose-500/10 text-rose-600 dark:text-rose-400 border-rose-500/20",
    summary: "Reveals active audio streams, display requests, and driver handles keeping your system awake.",
    summaryMs: "Memaparkan proses, audio, atau driver yang menghalang komputer daripada masuk mod Sleep.",
    commandOrAction: "powercfg /requests",
    isCommand: true,
    details: "Pinpoints misbehaving web players, background voice chats, or controller drivers blocking standby timer.",
    detailsMs: "Mengenal pasti tab pelayar, perisian sembang suara, atau peranti USB yang menahan komputer sentiasa menyala.",
    tags: ["sleep", "powercfg", "standby", "battery", "cmd"],
  },
  {
    id: "tip-driver-store-audit",
    category: "pc-tips",
    title: "Audit Injected OEM Drivers in Driver Store",
    titleMs: "Senaraikan Driver Pihak Ketiga (Driver Store)",
    badge: "Driver Health",
    badgeColor: "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/20",
    summary: "Lists all third-party OEM drivers installed in Windows with provider name, class, and version number.",
    summaryMs: "Menyenaraikan semua driver pihak ketiga dalam sistem untuk mengesan driver lapuk.",
    commandOrAction: "pnputil /enum-drivers",
    isCommand: true,
    details: "Spot obsolete or orphaned drivers (oemXX.inf) causing boot slowdowns. Remove with pnputil /delete-driver oemXX.inf /uninstall.",
    detailsMs: "Kesan driver lama yang menyebabkan masa boot lambat. Padam dengan arahan /delete-driver.",
    tags: ["drivers", "pnputil", "inf", "storage", "cleanup"],
  },
  {
    id: "tip-disk-health-ps",
    category: "pc-tips",
    title: "Physical Disk Health & Media Query",
    titleMs: "Semak Kesihatan & Jenis Storan Fizikal",
    badge: "Storage",
    badgeColor: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20",
    summary: "Displays drive model, media type (NVMe/SSD/HDD), bus interface, and low-level health status.",
    summaryMs: "Memaparkan model cakera, jenis storan (NVMe/SSD/HDD), dan status kesihatan perkakasan.",
    commandOrAction: "Get-PhysicalDisk | Select-Object FriendlyName, MediaType, BusType, HealthStatus, OperationalStatus",
    isCommand: true,
    details: "Quick PowerShell check to verify whether storage controller reports healthy operational state without extra software.",
    detailsMs: "Semakan pantas PowerShell untuk mengesahkan pemacu berfungsi normal tanpa perlu pasang perisian pihak ketiga.",
    tags: ["powershell", "disk", "ssd", "nvme", "storage"],
  },
  {
    id: "tip-port-lock-kill",
    category: "pc-tips",
    title: "Identify & Kill Process Locking a Network Port",
    titleMs: "Kesan & Tutup Proses Kunci Port Rangkaian",
    badge: "Network Debug",
    badgeColor: "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20",
    summary: "Finds PID listening on a blocked port (e.g. 3000 or 8080) and terminates it with immediate force.",
    summaryMs: "Cari PID yang menyekat port rangkaian dan matikan proses tersebut serta-merta.",
    commandOrAction: "netstat -ano | findstr :3000\ntaskkill /PID <PID> /F",
    isCommand: true,
    details: "Essential for web developers and gamers when local servers or background launchers refuse to bind port.",
    detailsMs: "Sangat berguna untuk pembangun web dan pemain game apabila port disekat oleh proses hantu.",
    tags: ["port", "netstat", "taskkill", "network", "developer"],
  },
  {
    id: "tip-flush-dns-renew",
    category: "pc-tips",
    title: "DNS Cache Flush & DHCP Lease Renew",
    titleMs: "Buang Cache DNS & Perbaharui IP",
    badge: "Networking",
    badgeColor: "bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 border-cyan-500/20",
    summary: "Purges corrupted local domain resolution records and renegotiates fresh IP assignment with gateway.",
    summaryMs: "Membersihkan rekod domain lapuk dan meminta alamat IP baharu daripada router.",
    commandOrAction: "ipconfig /flushdns && ipconfig /renew",
    isCommand: true,
    details: "Fixes sudden 'server IP address could not be found' browser errors following router restarts or DNS changes.",
    detailsMs: "Membaiki masalah pelayar web gagal cari laman web selepas restart router.",
    tags: ["dns", "ipconfig", "network", "internet", "fix"],
  },

  // ==========================================
  // 2. COOL TOOLS & DEBLOATERS
  // ==========================================
  {
    id: "tool-ctt-winutil",
    category: "cool-tools",
    title: "Chris Titus Tech Windows Utility (CTT WinUtil)",
    titleMs: "Utiliti Windows Chris Titus Tech (WinUtil)",
    badge: "Debloat & Tweaks",
    badgeColor: "bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-500/20",
    developer: "Chris Titus Tech & Community",
    officialUrl: "https://christitus.com/winutil",
    githubUrl: "https://github.com/ChrisTitusTech/winutil",
    summary: "All-in-one open-source utility for debloating Windows, toggling telemetry, and bulk installing software via winget.",
    summaryMs: "Perisian sumber terbuka serba lengkap untuk membuang bloatware Windows, mematikan telemetri, dan memasang aplikasi.",
    commandOrAction: 'irm "https://christitus.com/winutil" | iex',
    isCommand: true,
    details: "Launch via PowerShell as Administrator. Includes automatic system restore point creation, privacy tweaks, and update stabilization.",
    detailsMs: "Jalankan dalam PowerShell (Admin). Mengandungi fungsi cipta restore point automatik dan tetapan privasi.",
    safetyNote: "Always check 'Create Restore Point' first before applying system tweaks.",
    safetyNoteMs: "Sentiasa tekan 'Create Restore Point' sebelum memulakan tweak sistem.",
    tags: ["ctt", "winutil", "debloat", "tweaks", "open source"],
  },
  {
    id: "tool-oo-shutup10",
    category: "cool-tools",
    title: "O&O ShutUp10++",
    titleMs: "O&O ShutUp10++ (Kawalan Privasi)",
    badge: "Privacy & Telemetry",
    badgeColor: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20",
    developer: "O&O Software",
    officialUrl: "https://www.oo-software.com/en/shutup10",
    summary: "Free, portable privacy tool with color-coded toggles to disable intrusive Windows telemetry and ad tracking safely.",
    summaryMs: "Alatan mudah alih percuma dengan kod warna untuk mengawal privasi dan menyahaktifkan penjejakan iklan.",
    details: "Zero installation required. Uses green/yellow/red recommendations so users never accidentally break Windows Update or Store services.",
    detailsMs: "Tidak perlu pemasangan. Menggunakan cadangan warna hijau/kuning/merah supaya tidak memecahkan fungsi asas Windows.",
    tags: ["privacy", "telemetry", "portable", "free", "security"],
  },
  {
    id: "tool-atlasos",
    category: "cool-tools",
    title: "AtlasOS",
    titleMs: "AtlasOS (Modifikasi Prestasi)",
    badge: "Performance Playbook",
    badgeColor: "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/20",
    developer: "Atlas Team",
    officialUrl: "https://atlasos.net",
    githubUrl: "https://github.com/atlas-os/Atlas",
    summary: "Open-source Windows modification that reduces input latency, cuts background process bloat, and optimizes power schemes.",
    summaryMs: "Modifikasi Windows sumber terbuka untuk mengurangkan latency input dan mengurangkan penggunaan proses latar belakang.",
    details: "Aimed at PC gamers wanting lower DPC latency without sacrificing driver compatibility or security fundamentals.",
    detailsMs: "Direka khas untuk pemain game yang mahukan masa tindak balas pantas tanpa mengorbankan kestabilan driver.",
    tags: ["atlasos", "latency", "gaming", "debloat", "open source"],
  },
  {
    id: "tool-ddu",
    category: "cool-tools",
    title: "Display Driver Uninstaller (DDU)",
    titleMs: "Display Driver Uninstaller (DDU)",
    badge: "GPU Maintenance",
    badgeColor: "bg-rose-500/10 text-rose-600 dark:text-rose-400 border-rose-500/20",
    developer: "Wagnardsoft",
    officialUrl: "https://www.wagnardsoft.com",
    summary: "Boots into Safe Mode to completely clean GPU drivers, registries, and leftovers from NVIDIA, AMD, or Intel.",
    summaryMs: "Membuang sepenuhnya fail, pendaftaran, dan sisa pemacu GPU dalam mod Safe Mode.",
    details: "Gold standard on r/pcmasterrace for fixing black screens, micro-stutters, and driver conflicts after installing a new graphics card.",
    detailsMs: "Standard utama komuniti PC untuk membaiki masalah skrin hitam dan sangkut selepas tukar kad grafik baharu.",
    safetyNote: "Always execute while booted into Windows Safe Mode with internet disconnected.",
    safetyNoteMs: "Sentiasa jalankan dalam Windows Safe Mode dengan sambungan internet diputuskan.",
    tags: ["ddu", "gpu", "nvidia", "amd", "display", "driver"],
  },
  {
    id: "tool-everything",
    category: "cool-tools",
    title: "Everything",
    titleMs: "Everything (Carian Fail Kilat)",
    badge: "Search Engine",
    badgeColor: "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20",
    developer: "Voidtools (David Carpenter)",
    officialUrl: "https://www.voidtools.com",
    summary: "Instantaneous desktop search engine reading the NTFS Master File Table directly, searching millions of files in milliseconds.",
    summaryMs: "Enjin carian desktop segera membaca Master File Table NTFS, mencari jutaan fail dalam milisaat.",
    details: "Replaces slow Windows Search. Consumes virtually zero background CPU and under 50 MB RAM while indexing local and external drives.",
    detailsMs: "Menggantikan carian Windows yang perlahan. Menggunakan RAM bawah 50MB dan carian sepantas kilat.",
    tags: ["everything", "search", "voidtools", "ntfs", "fast"],
  },
  {
    id: "tool-wiztree",
    category: "cool-tools",
    title: "WizTree",
    titleMs: "WizTree (Analisis Ruang Storan)",
    badge: "Disk Analyzer",
    badgeColor: "bg-sky-500/10 text-sky-600 dark:text-sky-400 border-sky-500/20",
    developer: "Antibody Software",
    officialUrl: "https://diskanalyzer.com",
    summary: "High-speed disk space visualizer that parses the NTFS MFT in seconds (46x faster than WinDirStat) with interactive treemaps.",
    summaryMs: "Penganalisis ruang cakera berkelajuan tinggi yang mengimbas MFT dalam beberapa saat dengan visual treemap.",
    details: "Quickly spots hidden bloatware, forgotten game installs, oversized temp files, and driver log dumps.",
    detailsMs: "Mengesan fail gergasi, game lama, dan folder sampah tersembunyi dengan pantas.",
    tags: ["wiztree", "storage", "disk", "cleanup", "treemap"],
  },
  {
    id: "tool-crystaldiskinfo",
    category: "cool-tools",
    title: "CrystalDiskInfo",
    titleMs: "CrystalDiskInfo (Kesihatan SSD & HDD)",
    badge: "SMART Health",
    badgeColor: "bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border-indigo-500/20",
    developer: "Noriyuki Miyazaki (hiyohiyo)",
    officialUrl: "https://crystalmark.info/en/software/crystaldiskinfo/",
    githubUrl: "https://github.com/hiyohiyo/CrystalDiskInfo",
    summary: "Reads low-level SMART telemetry, TBW lifespan, reallocated sectors, and real-time temperatures for NVMe, SATA SSDs, and HDDs.",
    summaryMs: "Membaca data SMART, jangka hayat TBW, dan suhu masa nyata untuk pemacu NVMe, SSD, dan HDD.",
    details: "Provides early caution warnings when storage units begin degrading before catastrophic hardware failure strikes.",
    detailsMs: "Memberi amaran awal sebelum pemacu storan rosak sepenuhnya dan data hilang.",
    tags: ["crystaldiskinfo", "smart", "ssd", "nvme", "health"],
  },
  {
    id: "tool-hwinfo64",
    category: "cool-tools",
    title: "HWiNFO64",
    titleMs: "HWiNFO64 (Sensor Perkakasan Terperinci)",
    badge: "Hardware Telemetry",
    badgeColor: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20",
    developer: "Martin Malik (REALiX)",
    officialUrl: "https://www.hwinfo.com",
    summary: "Exhaustive hardware sensor monitoring: per-core CPU temps, GPU hotspot, VRAM junction temp, VRM thermal sensors, and wattage.",
    summaryMs: "Pemantauan sensor perkakasan lengkap: suhu CPU terperinci, hotspot GPU, VRAM, dan voltan bekalan kuasa.",
    details: "Displays exact silicon throttle flags (Thermal Throttling, Power Limit, Voltage Reliability) during heavy gaming or rendering.",
    detailsMs: "Memaparkan sebab sebenar komputer perlahan seperti kepanasan atau had kuasa elektrik.",
    tags: ["hwinfo", "monitoring", "sensors", "gpu", "cpu", "thermal"],
  },
  {
    id: "tool-fancontrol",
    category: "cool-tools",
    title: "Fan Control",
    titleMs: "Fan Control (Kawalan Kipas Khas)",
    badge: "Thermal Management",
    badgeColor: "bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 border-cyan-500/20",
    developer: "Rem0o",
    githubUrl: "https://github.com/Rem0o/FanControl.Releases",
    summary: "Unified custom fan curve manager combining CPU, GPU, and motherboard thermal probes to drive custom fan profiles.",
    summaryMs: "Pengurus kelajuan kipas khas yang menggabungkan sensor CPU dan GPU untuk kawalan aliran udara optimal.",
    details: "Allows case intake and exhaust fans to ramp up based on graphics card temperatures rather than only processor spikes.",
    detailsMs: "Membolehkan kipas casing berpusing mengikut suhu kad grafik dan bukannya CPU semata-mata.",
    tags: ["fans", "cooling", "gpu", "open source", "thermal"],
  },
  {
    id: "tool-latencymon",
    category: "cool-tools",
    title: "LatencyMon",
    titleMs: "LatencyMon (Kesan Punca Lag Audio)",
    badge: "Audio & DPC Latency",
    badgeColor: "bg-rose-500/10 text-rose-600 dark:text-rose-400 border-rose-500/20",
    developer: "Resplendence Software",
    officialUrl: "https://www.resplendence.com/latencymon",
    summary: "Measures DPC and ISR execution times to name the exact driver causing audio pops, clicks, or micro-stutters in games.",
    summaryMs: "Mengukur masa tindak balas DPC/ISR untuk mengenal pasti pemacu yang menyebabkan bunyi pecah atau micro-stutter.",
    details: "Reveals whether network drivers (ndis.sys), GPU drivers (nvlddmkm.sys), or storage controllers are spiking latency.",
    detailsMs: "Mendedahkan jika driver Wi-Fi, kad grafik, atau storan menjadi punca lag.",
    tags: ["latencymon", "dpc", "audio", "stutter", "drivers"],
  },
  {
    id: "tool-powertoys",
    category: "cool-tools",
    title: "Microsoft PowerToys",
    titleMs: "Microsoft PowerToys (Alatan Produktiviti)",
    badge: "Productivity",
    badgeColor: "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/20",
    developer: "Microsoft & Open Source Community",
    githubUrl: "https://github.com/microsoft/PowerToys",
    summary: "Official system tuning suite: FancyZones window snapping, Text Extractor OCR (Win+Shift+T), and Always On Top (Win+Ctrl+T).",
    summaryMs: "Himpunan alatan rasmi Microsoft: susunan tetingkap FancyZones, salin teks gambar OCR, dan semat tetingkap.",
    details: "Supercharges multi-monitor workflows with quick keyboard launcher, image resizer, and plain-text pasting.",
    detailsMs: "Meningkatkan produktiviti dengan pintasan papan kekunci, pengubah saiz imej, dan pemilih warna skrin.",
    tags: ["powertoys", "microsoft", "productivity", "fancyzones", "ocr"],
  },
  {
    id: "tool-rufus",
    category: "cool-tools",
    title: "Rufus",
    titleMs: "Rufus (Pencipta USB Bootable)",
    badge: "Boot Media",
    badgeColor: "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20",
    developer: "Pete Batard",
    officialUrl: "https://rufus.ie",
    githubUrl: "https://github.com/pbatard/rufus",
    summary: "Creates bootable USB installation flash drives with built-in toggles to bypass Windows 11 TPM 2.0, Secure Boot, and Microsoft Account requirements.",
    summaryMs: "Mencipta pendrive bootable dengan fungsi melangkau syarat TPM 2.0, Secure Boot, dan akaun Microsoft.",
    details: "Lightweight, portable, and fast. Lets you create clean local user accounts automatically during installation.",
    detailsMs: "Ringan, pantas, dan membolehkan pemasangan akaun tempatan (offline) dibuat secara automatik.",
    tags: ["rufus", "usb", "bootable", "windows 11", "tpm bypass"],
  },
  {
    id: "tool-ventoy",
    category: "cool-tools",
    title: "Ventoy",
    titleMs: "Ventoy (Multiboot USB Mudah)",
    badge: "Boot Media",
    badgeColor: "bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-500/20",
    developer: "longpanda",
    officialUrl: "https://www.ventoy.net",
    githubUrl: "https://github.com/ventoy/Ventoy",
    summary: "Turns a USB flash drive into a multi-boot disk where you simply drag-and-drop ISO files without reformatting.",
    summaryMs: "Menjadikan pendrive USB pemacu pelbagai boot dengan hanya memasukkan fail ISO secara drag-and-drop.",
    details: "Carry Windows 10/11 installers, Ubuntu, MemTest, and Clonezilla all on a single flash drive simultaneously.",
    detailsMs: "Muatkan installer Windows, Linux, dan alatan pembaikan komputer pada satu pendrive yang sama.",
    tags: ["ventoy", "multiboot", "iso", "usb", "open source"],
  },
  {
    id: "tool-eartrumpet",
    category: "cool-tools",
    title: "EarTrumpet",
    titleMs: "EarTrumpet (Pengadun Audio Moden)",
    badge: "Audio Management",
    badgeColor: "bg-sky-500/10 text-sky-600 dark:text-sky-400 border-sky-500/20",
    developer: "File-New-Project",
    githubUrl: "https://github.com/File-New-Project/EarTrumpet",
    summary: "Replaces default Windows audio tray with an elegant per-application volume mixer and instant output device switching.",
    summaryMs: "Menggantikan ikon bunyi Windows dengan pengadun volume bagi setiap aplikasi secara berasingan.",
    details: "Control game, Discord, and browser volumes individually with two clicks from the taskbar.",
    detailsMs: "Kawal kekuatan bunyi game, Discord, dan YouTube secara berasingan dengan mudah dari taskbar.",
    tags: ["eartrumpet", "audio", "volume", "sound", "mixer"],
  },
  {
    id: "tool-screentogif",
    category: "cool-tools",
    title: "ScreenToGif",
    titleMs: "ScreenToGif (Perakam Skrin & Editor GIF)",
    badge: "Media Recording",
    badgeColor: "bg-rose-500/10 text-rose-600 dark:text-rose-400 border-rose-500/20",
    developer: "Nicke Manarin",
    officialUrl: "https://www.screentogif.com",
    githubUrl: "https://github.com/NickeManarin/ScreenToGif",
    summary: "Lightweight screen, webcam, and sketchboard recorder with built-in frame editor to create optimized bug reproduction GIFs.",
    summaryMs: "Perakam skrin ringan dengan editor setiap bingkai untuk menghasilkan animasi GIF demonstrasi.",
    details: "Remove unwanted frames, add keystroke highlights, crop borders, and export directly to GIF, APNG, or MP4.",
    detailsMs: "Potong bingkai yang tidak diingini, paparkan butang papan kekunci, dan simpan sebagai fail animasi ringan.",
    tags: ["screentogif", "screen recorder", "gif", "tutorial", "media"],
  },
  {
    id: "tool-bcuninstaller",
    category: "cool-tools",
    title: "Bulk Crap Uninstaller (BCU)",
    titleMs: "Bulk Crap Uninstaller (Nyahpasang Bersih)",
    badge: "Software Uninstaller",
    badgeColor: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20",
    developer: "Marcin Szeniak (Klocman)",
    officialUrl: "https://www.bcuninstaller.com",
    githubUrl: "https://github.com/Klocman/Bulk-Crap-Uninstaller",
    summary: "Automated batch uninstaller that removes multiple applications in silence and aggressively scrubs leftover registry keys and files.",
    summaryMs: "Nyahpasang pelbagai perisian secara serentak dan membersihkan sisa pendaftaran serta folder tersembunyi.",
    details: "Detects portable tools, Steam games, Windows Store apps, and stubborn bloatware with zero manual clicking.",
    detailsMs: "Mengesan aplikasi mudah alih dan perisian degil tanpa perlu menekan butang uninstall satu per satu.",
    tags: ["bcuninstaller", "uninstaller", "cleanup", "registry", "bloatware"],
  },
  {
    id: "tool-islc",
    category: "cool-tools",
    title: "Intelligent Standby List Cleaner (ISLC)",
    titleMs: "Intelligent Standby List Cleaner (Pembersih Cache RAM)",
    badge: "RAM & Latency",
    badgeColor: "bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-500/20",
    developer: "Wagnardsoft (Creator of DDU)",
    officialUrl: "https://www.wagnardsoft.com/forums/viewtopic.php?t=1256",
    summary: "Automatically purges dormant Windows Standby memory cache to cure micro-stutter in games, and locks timer resolution to 0.50ms.",
    summaryMs: "Membersihkan cache memori 'Standby' Windows secara automatik untuk mengatasi masalah lag mikro (stutter) dalam game, serta mengunci timer resolution pada 0.50ms.",
    details: "Unlike blind RAM cleaners, ISLC never purges active Working Sets, avoiding hard page faults, disk thrashing, and frame drops.",
    detailsMs: "Tidak seperti pembersih RAM lain yang merosakkan prestasi, ISLC hanya membersihkan memori tidak aktif dan tidak memaksa data program ke dalam fail paging storan.",
    safetyNote: "Set 'The list size is at least' to 1024MB and 'Free memory is lower than' to half your total RAM.",
    safetyNoteMs: "Tetapkan saiz senarai minimum kepada 1024MB dan had memori bebas kepada separuh daripada kapasiti RAM anda.",
    tags: ["islc", "ram", "standby list", "stutter", "gaming", "latency", "wagnardsoft"],
  },
  {
    id: "tool-rammap",
    category: "cool-tools",
    title: "Microsoft Sysinternals RAMMap",
    titleMs: "Microsoft Sysinternals RAMMap (Analisis Memori)",
    badge: "Memory Diagnostics",
    badgeColor: "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/20",
    developer: "Mark Russinovich (Microsoft Sysinternals)",
    officialUrl: "https://learn.microsoft.com/en-us/sysinternals/downloads/rammap",
    summary: "Official Microsoft physical memory utility to analyze active processes, kernel pools, and file cache with safe manual cache purging.",
    summaryMs: "Utiliti rasmi Microsoft untuk menganalisis penggunaan memori fizikal, cache fail, dan membersihkan senarai standby secara manual dan selamat.",
    details: "Safest official tool to inspect and flush the standby list (Empty > Empty Standby List) without unverified third-party background services.",
    detailsMs: "Cara rasmi dan paling selamat untuk memeriksa serta membersihkan senarai memori standby tanpa memasang perisian pihak ketiga yang tidak diketahui.",
    safetyNote: "Use Empty > Empty Standby List only. Avoid 'Empty Working Sets' as it forces disk paging.",
    safetyNoteMs: "Gunakan pilihan 'Empty Standby List' sahaja. Elakkan 'Empty Working Sets' kerana ia memaksa pemacu storan bekerja keras.",
    tags: ["rammap", "sysinternals", "microsoft", "ram", "standby", "memory", "diagnostics"],
  },

  // ==========================================
  // 3. FUN STUFF, SECRETS & EASTER EGGS
  // ==========================================
  {
    id: "fun-slidetoshutdown",
    category: "fun-stuff",
    title: "SlideToShutdown Full-Screen Curtain",
    titleMs: "Tirai Skrin Penuh SlideToShutdown",
    badge: "Hidden UI",
    badgeColor: "bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-500/20",
    summary: "Summons a touch-friendly lock screen shade that drops down with the prompt 'Slide to shut down your PC'.",
    summaryMs: "Membuka tirai skrin sentuh yang meluncur ke bawah untuk mematikan komputer dengan gaya.",
    commandOrAction: "SlideToShutdown.exe",
    isCommand: true,
    details: "Press Win + R, type SlideToShutdown.exe, and press Enter. Pull shade down to shut down, or slide up to cancel.",
    detailsMs: "Tekan Win + R, taip SlideToShutdown.exe dan tekan Enter. Tarik tirai ke bawah untuk tutup PC.",
    tags: ["slidetoshutdown", "easter egg", "shutdown", "touch", "secret"],
  },
  {
    id: "fun-gpu-reset",
    category: "fun-stuff",
    title: "Instant Graphics Subsystem Driver Kick",
    titleMs: "Pintasan Mulakan Semula Driver Grafik",
    badge: "Recovery Shortcut",
    badgeColor: "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20",
    summary: "Display flickers black, beeps once, and restarts Desktop Window Manager (DWM) without closing games or rebooting.",
    summaryMs: "Skrin berkelip seketika, berbunyi beep, dan memulakan semula subsystem grafik tanpa perlu restart.",
    commandOrAction: "Win + Ctrl + Shift + B",
    isCommand: false,
    details: "Designed by Microsoft to unfreeze black screens, display handshake glitches, or frozen video buffers on the fly.",
    detailsMs: "Direka oleh Microsoft untuk memulihkan skrin hitam atau gambar tergantung semasa bermain game.",
    tags: ["hotkey", "gpu reset", "display", "shortcut", "secret"],
  },
  {
    id: "fun-setup-bypassnro",
    category: "fun-stuff",
    title: "Windows 11 Setup Offline Local Account Bypass",
    titleMs: "Langkau Akaun Microsoft Semasa Setup Win 11",
    badge: "Setup Hack",
    badgeColor: "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/20",
    summary: "Unlocks the 'I don't have internet' button on Windows 11 installation screen to create a pure local offline account.",
    summaryMs: "Membuka butang 'Tiada sambungan internet' semasa pemasangan Windows 11 untuk akaun tempatan.",
    commandOrAction: "Shift + F10\noobe\\bypassnro",
    isCommand: true,
    details: "At the network connection setup screen, press Shift + F10 to launch CMD, run oobe\\bypassnro, and your PC will reboot with offline options unlocked.",
    detailsMs: "Pada skrin sambungan internet pemasangan, tekan Shift + F10, taip oobe\\bypassnro dan tekan Enter.",
    tags: ["bypassnro", "windows 11", "setup", "offline", "local account"],
  },
  {
    id: "fun-reliability-monitor",
    category: "fun-stuff",
    title: "Reliability Monitor Hidden Stability Index",
    titleMs: "Graf Kestabilan Sistem (Reliability Monitor)",
    badge: "Hidden Diagnostic",
    badgeColor: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20",
    summary: "Displays a visual 1-to-10 stability score graph over past weeks, charting app crashes, Windows updates, and blue screens.",
    summaryMs: "Memaparkan graf indeks kestabilan 1 hingga 10 yang merekodkan setiap crash aplikasi dan kemaskini.",
    commandOrAction: "perfmon /rel",
    isCommand: true,
    details: "Press Win + R, type perfmon /rel, and press Enter. The easiest way to see what software broke your PC on a specific date.",
    detailsMs: "Tekan Win + R, taip perfmon /rel dan tekan Enter. Cara paling mudah menyemak punca kerosakan mengikut tarikh.",
    tags: ["reliability monitor", "perfmon", "crash history", "diagnostic", "hidden"],
  },
  {
    id: "fun-con-folder-quirk",
    category: "fun-stuff",
    title: "Reserved DOS Device Names (CON, PRN, AUX, NUL)",
    titleMs: "Nama Fail Terlarang Era DOS (CON, PRN, AUX)",
    badge: "Vintage OS Quirk",
    badgeColor: "bg-rose-500/10 text-rose-600 dark:text-rose-400 border-rose-500/20",
    summary: "Windows forbids creating folders named CON, PRN, AUX, NUL, COM1-9, or LPT1-9 due to 1974 CP/M and 1981 DOS compatibility.",
    summaryMs: "Windows melarang ciptaan folder bernama CON, PRN, AUX kerana keserasian warisan DOS 1981.",
    details: "In original MS-DOS, hardware devices were treated as virtual files. The check remains active today in Windows 11 Explorer.",
    detailsMs: "Dalam sistem DOS, peranti port perkakasan dianggap sebagai fail khas dan larangan ini kekal sehingga Windows 11.",
    tags: ["con", "dos", "easter egg", "history", "windows quirk"],
  },
  {
    id: "fun-ascii-starwars",
    category: "fun-stuff",
    title: "ASCII Star Wars in Command Prompt",
    titleMs: "Filem Star Wars Huruf ASCII Dalam Terminal",
    badge: "Terminal Retro",
    badgeColor: "bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 border-cyan-500/20",
    summary: "Streams the full Star Wars Episode IV animated movie rendered entirely in ASCII text characters inside CMD.",
    summaryMs: "Memainkan keseluruhan animasi filem Star Wars Episode IV dalam tulisan teks ASCII di Command Prompt.",
    commandOrAction: "curl telnet://telehack.com\nstarwars",
    isCommand: true,
    details: "Run command in Command Prompt or PowerShell, then type 'starwars' at the telehack prompt. Created by Simon Jansen.",
    detailsMs: "Jalankan dalam Command Prompt, kemudian taip starwars pada prompt telehack. Karya seni Simon Jansen.",
    tags: ["star wars", "ascii", "telehack", "terminal", "easter egg"],
  },
  {
    id: "fun-notepad-log",
    category: "fun-stuff",
    title: "Notepad Auto-Timestamp Journal (.LOG)",
    titleMs: "Buku Catatan Cap Masa Automatik Notepad",
    badge: "Built-In Feature",
    badgeColor: "bg-sky-500/10 text-sky-600 dark:text-sky-400 border-sky-500/20",
    summary: "Type .LOG as the first line of a text file in Notepad; every time you reopen it, the current date and time are stamped automatically.",
    summaryMs: "Tulis .LOG pada baris pertama fail teks Notepad; cap tarikh dan masa dimasukkan secara automatik setiap kali dibuka.",
    commandOrAction: ".LOG",
    isCommand: false,
    details: "A built-in feature preserved since Windows 3.1 in 1992. Positions the cursor immediately beneath for fast daily logging.",
    detailsMs: "Ciri tersembunyi yang wujud sejak Windows 3.1 pada tahun 1992 untuk catatan diari pantas.",
    tags: ["notepad", "log", "timestamp", "journal", "hidden feature"],
  },
  {
    id: "fun-aero-shake",
    category: "fun-stuff",
    title: "Aero Shake Window Minimizer",
    titleMs: "Goyang Tetingkap (Aero Shake Minimizer)",
    badge: "Desktop Gesture",
    badgeColor: "bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border-indigo-500/20",
    summary: "Grab active window title bar and shake mouse left and right; all background windows instantly minimize to taskbar.",
    summaryMs: "Pegang palang tajuk tetingkap dan goyang tetikus ke kiri kanan untuk meminimumkan semua tetingkap lain.",
    details: "Shake title bar again to restore windows. Toggle on/off in Windows 11 under Settings > System > Multitasking > Title bar window shake.",
    detailsMs: "Goyang sekali lagi untuk memulihkan tetingkap. Boleh diaktifkan dalam Tetapan > Sistem > Pelbagai Tugas.",
    tags: ["aero shake", "gesture", "desktop", "windows", "trick"],
  },
  {
    id: "fun-edge-surf",
    category: "fun-stuff",
    title: "Edge Offline Surfing Arcade Game",
    titleMs: "Permainan Luncur Air Tersembunyi Edge",
    badge: "Arcade Minigame",
    badgeColor: "bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-500/20",
    summary: "Full 8-bit retro surfing game built into Microsoft Edge with obstacles, ramps, time trial mode, and a kraken boss fight.",
    summaryMs: "Permainan luncur air retro 8-bit terbina dalam pelayar Microsoft Edge dengan halangan dan raksasa kraken.",
    commandOrAction: "edge://surf",
    isCommand: false,
    details: "Navigate to edge://surf in Microsoft Edge. Works completely offline with keyboard, mouse, touch, or gamepad support.",
    detailsMs: "Buka pelayar Microsoft Edge dan taip edge://surf. Boleh dimainkan secara offline sepenuhnya.",
    tags: ["edge", "surf", "game", "minigame", "easter egg"],
  },
  {
    id: "fun-solitaire-cascade",
    category: "fun-stuff",
    title: "Classic Solitaire Instant Win Cascade",
    titleMs: "Kemenangan Segera Solitaire Klasik",
    badge: "Retro Easter Egg",
    badgeColor: "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20",
    summary: "Press Alt + Shift + 2 in classic Windows Solitaire to trigger the iconic bouncing card victory celebration immediately.",
    summaryMs: "Tekan Alt + Shift + 2 dalam permainan Solitaire klasik untuk mencetuskan animasi kemenangan kad melantun serta-merta.",
    commandOrAction: "Alt + Shift + 2",
    isCommand: false,
    details: "Programmed into Windows Solitaire by Microsoft developer Wes Cherry in 1989 for rapid game win state testing.",
    detailsMs: "Diprogramkan oleh pembangun Microsoft Wes Cherry pada 1989 untuk menguji skrin animasi kemenangan.",
    tags: ["solitaire", "cards", "easter egg", "retro", "win"],
  },
  {
    id: "fun-space-cadet-pinball",
    category: "fun-stuff",
    title: "Space Cadet Pinball Ball Drag Cheat",
    titleMs: "Tip Kawalan Bebas Bola Space Cadet Pinball",
    badge: "Retro Cheat Code",
    badgeColor: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20",
    summary: "Type 'hidden test' in 3D Pinball Space Cadet to grab the ball with mouse cursor and trigger infinite points.",
    summaryMs: "Taip 'hidden test' dalam Space Cadet Pinball untuk menggerakkan bola pinball menggunakan tetikus secara bebas.",
    commandOrAction: "hidden test",
    isCommand: false,
    details: "Launch Windows NT / XP Space Cadet Pinball, type 'hidden test' with mouse clicked inside window, and click and drag the pinball freely.",
    detailsMs: "Buka game Space Cadet Pinball, taip hidden test, dan anda boleh tarik bola pinball ke mana-mana dengan tetikus.",
    tags: ["pinball", "space cadet", "cheat code", "retro", "windows xp"],
  },
];
